# =============================================================================
# dns_server — Authoritative DNS Server
# =============================================================================
#
# Targets:
#   make              → production build (optimised, stripped, signed)
#   make prod         → same as above
#   make debug        → debug build (symbols, sanitisers, no stripping)
#   make clean        → remove all build artefacts
#   make sign         → (re-)sign an already-built production binary
#   make verify       → verify signature on production binary
#   make install      → install production binary + signature to $(DESTDIR)$(PREFIX)/bin
#   make uninstall    → remove installed files
#   make check        → quick smoke-test (requires a running Valkey on 127.0.0.1:6379)
#
# Signing:
#   The production binary is signed with GPG (detached, armoured .asc signature).
#   To use your own key:
#       make prod GPG_KEY=<fingerprint-or-email>
#   To sign with a dedicated code-signing key generated by this Makefile:
#       make gen-signing-key     → create keys/codesign.{key,crt} (Ed25519, self-signed)
#       make                     → build + GPG-sign with $(GPG_KEY)
#   The OpenSSL raw-signature target (sign-openssl) produces a SHA-256/Ed25519
#   signature file alongside the GPG .asc, so deployments that cannot use GPG
#   can verify with openssl dgst.
#
# =============================================================================

# ── Source & output names ────────────────────────────────────────────────────
SRC        := dns_server.c
BIN        := dns_server
BIN_DEBUG  := dns_server_debug
SIG_GPG    := $(BIN).asc
SIG_OSSL   := $(BIN).sig
OSSL_PUBKEY := keys/codesign.pub.pem

# ── Install paths ────────────────────────────────────────────────────────────
PREFIX     ?= /usr/local
DESTDIR    ?=
BINDIR      = $(DESTDIR)$(PREFIX)/bin
SIGDIR      = $(DESTDIR)$(PREFIX)/share/dns_server/signatures

# ── Compiler ─────────────────────────────────────────────────────────────────
CC         ?= gcc
CSTD        = -std=c99 -D_GNU_SOURCE

# ── OpenSSL paths (override on the command line if non-standard) ─────────────
#   Example: make OSSL_INC=/opt/openssl/include OSSL_LIB=/opt/openssl/lib
OSSL_INC   ?= /tmp/ossl-inc
OSSL_LIB   ?= /usr/local/lib

# ── Signing ──────────────────────────────────────────────────────────────────
# GPG key fingerprint / email to sign with.
# Defaults to the first secret key in the keyring; set explicitly for CI.
GPG_KEY    ?=
GPG_SIGN    = gpg --batch --yes --armor --detach-sign
ifneq ($(strip $(GPG_KEY)),)
GPG_SIGN   += --local-user "$(GPG_KEY)"
endif

# OpenSSL Ed25519 key for the secondary raw-signature (optional).
OSSL_SIGN_KEY ?= keys/codesign.key.pem

# ── Common compile flags ─────────────────────────────────────────────────────
WARN       := -Wall -Wextra -Wformat=2 -Wformat-overflow=2 \
              -Wnull-dereference -Wstack-protector \
              -Wno-unused-parameter -Wno-missing-field-initializers \
              -Wno-implicit-fallthrough

INCLUDES   := -I$(OSSL_INC)
LIBS       := -L$(OSSL_LIB) -lssl -lcrypto -lpthread -Wl,-rpath,$(OSSL_LIB)

# ── Production flags ─────────────────────────────────────────────────────────
#   -O2          : safe optimisation level for a server daemon
#   -fstack-protector-strong : stack-smashing protection
#   -D_FORTIFY_SOURCE=2      : glibc buffer-overflow detection
#   -fPIE / -pie             : position-independent executable (ASLR)
#   -Wl,-z,relro,-z,now      : read-only relocations, immediate binding
PROD_FLAGS := -O2 \
              -fstack-protector-strong \
              -D_FORTIFY_SOURCE=2 \
              -fPIE \
              -pie -Wl,-z,relro,-z,now

# ── Debug flags ──────────────────────────────────────────────────────────────
#   -Og          : optimise for debugging (readable code, no inlining)
#   -g3 -ggdb    : maximum DWARF info
#   -fsanitize   : AddressSanitizer + UBSanitizer
#   -fno-omit-frame-pointer : accurate stack traces under ASan
DEBUG_FLAGS := -Og -g3 -ggdb \
               -fsanitize=address,undefined \
               -fno-omit-frame-pointer \
               -DDEBUG

# ── Build version string (embedded via -DBUILD_VERSION) ─────────────────────
GIT_SHA    := $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_DATE := $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
VERSION_FLAGS := -DBUILD_VERSION='"$(GIT_SHA)"' -DBUILD_DATE='"$(BUILD_DATE)"'

# =============================================================================
# Phony targets
# =============================================================================
.PHONY: all prod debug clean sign sign-openssl verify install uninstall \
        check gen-signing-key help

# Default → production
all: prod

# =============================================================================
# Production build
# =============================================================================
prod: $(BIN) sign

$(BIN): $(SRC)
	@echo "  CC [PROD]  $@"
	$(CC) $(CSTD) $(WARN) $(PROD_FLAGS) $(VERSION_FLAGS) \
	      $(INCLUDES) -o $@ $^ $(LIBS)
	@echo "  STRIP      $@"
	strip --strip-unneeded \
	      --remove-section=.comment \
	      --remove-section=.note \
	      $@
	@echo "  SIZE       $@"
	@size $@
	@echo ""
	@echo "  Production binary: $@ (stripped, hardened)"

# =============================================================================
# Debug build
# =============================================================================
debug: $(BIN_DEBUG)

$(BIN_DEBUG): $(SRC)
	@echo "  CC [DEBUG] $@"
	$(CC) $(CSTD) $(WARN) $(DEBUG_FLAGS) $(VERSION_FLAGS) \
	      $(INCLUDES) -o $@ $^ $(LIBS)
	@echo ""
	@echo "  Debug binary: $@  (ASan/UBSan enabled — do NOT use in production)"
	@echo "  Run as:  ASAN_OPTIONS=detect_leaks=1 ./$@"

# =============================================================================
# Signing
# =============================================================================

# GPG detached armoured signature
sign: $(BIN)
	@echo "  SIGN [GPG] $(BIN) → $(SIG_GPG)"
	$(GPG_SIGN) --output $(SIG_GPG) $(BIN)
	@echo "  GPG signature written: $(SIG_GPG)"
	@echo ""
	@gpg --batch --verify $(SIG_GPG) $(BIN) && \
	    echo "  ✓ Signature verified OK" || \
	    (echo "  ✗ Signature verification FAILED"; exit 1)

# OpenSSL Ed25519 raw-signature (secondary, non-GPG environments)
sign-openssl: $(BIN) $(OSSL_SIGN_KEY)
	@echo "  SIGN [OSSL] $(BIN) → $(SIG_OSSL)"
	openssl dgst -sha256 -sign $(OSSL_SIGN_KEY) \
	        -out $(SIG_OSSL) $(BIN)
	@echo "  OpenSSL signature written: $(SIG_OSSL)"
	@echo "  Verify with:"
	@echo "    openssl dgst -sha256 -verify $(OSSL_PUBKEY) -signature $(SIG_OSSL) $(BIN)"

# =============================================================================
# Verification
# =============================================================================
verify: $(BIN) $(SIG_GPG)
	@echo "  VERIFY [GPG] $(SIG_GPG)"
	@gpg --batch --verify $(SIG_GPG) $(BIN) && \
	    echo "  ✓  GPG signature is valid" || \
	    (echo "  ✗  GPG signature is INVALID or key not trusted"; exit 1)
	@if [ -f $(SIG_OSSL) ] && [ -f $(OSSL_PUBKEY) ]; then \
	    echo "  VERIFY [OSSL] $(SIG_OSSL)"; \
	    openssl dgst -sha256 -verify $(OSSL_PUBKEY) \
	            -signature $(SIG_OSSL) $(BIN) && \
	        echo "  ✓  OpenSSL signature is valid" || \
	        echo "  ✗  OpenSSL signature is INVALID"; \
	fi

# =============================================================================
# Code-signing key generation (one-time setup)
# =============================================================================
gen-signing-key:
	@mkdir -p keys
	@echo "  GEN  Ed25519 code-signing key pair → keys/codesign.{key,pub}.pem"
	openssl genpkey -algorithm ed25519 -out keys/codesign.key.pem
	openssl pkey -in keys/codesign.key.pem -pubout -out keys/codesign.pub.pem
	@echo ""
	@echo "  Self-signed certificate (for reference / TLSA/DANE use):"
	openssl req -new -x509 -days 3650 \
	        -key keys/codesign.key.pem \
	        -out keys/codesign.crt \
	        -subj "/CN=dns_server-codesign/O=Local/C=US"
	@chmod 600 keys/codesign.key.pem
	@echo ""
	@echo "  ✓  Keys generated. Keep keys/codesign.key.pem secret."
	@echo "     Distribute keys/codesign.pub.pem to verifiers."
	@echo ""
	@echo "  To generate a GPG code-signing key:"
	@echo "    gpg --batch --gen-key <<EOF"
	@echo "    %no-protection"
	@echo "    Key-Type: ed25519"
	@echo "    Key-Usage: sign"
	@echo "    Name-Real: dns_server codesign"
	@echo "    Name-Email: codesign@example.local"
	@echo "    Expire-Date: 2y"
	@echo "    %commit"
	@echo "    EOF"
	@echo "  Then: make prod GPG_KEY=codesign@example.local"

# =============================================================================
# Install
# =============================================================================
install: $(BIN) $(SIG_GPG)
	@echo "  INSTALL $(BIN) → $(BINDIR)/$(BIN)"
	install -d $(BINDIR)
	install -m 0755 $(BIN) $(BINDIR)/$(BIN)
	@echo "  INSTALL $(SIG_GPG) → $(SIGDIR)/$(SIG_GPG)"
	install -d $(SIGDIR)
	install -m 0644 $(SIG_GPG) $(SIGDIR)/$(SIG_GPG)
	@if [ -f $(SIG_OSSL) ]; then \
	    echo "  INSTALL $(SIG_OSSL) → $(SIGDIR)/$(SIG_OSSL)"; \
	    install -m 0644 $(SIG_OSSL) $(SIGDIR)/$(SIG_OSSL); \
	fi
	@echo ""
	@echo "  ✓  Installed. Verify on target with:"
	@echo "     gpg --verify $(SIGDIR)/$(SIG_GPG) $(BINDIR)/$(BIN)"

uninstall:
	@echo "  REMOVE $(BINDIR)/$(BIN)"
	rm -f $(BINDIR)/$(BIN)
	@echo "  REMOVE $(SIGDIR)/$(SIG_GPG) $(SIGDIR)/$(SIG_OSSL)"
	rm -f $(SIGDIR)/$(SIG_GPG) $(SIGDIR)/$(SIG_OSSL)
	@rmdir --ignore-fail-on-non-empty $(SIGDIR) 2>/dev/null || true

# =============================================================================
# Smoke test
# =============================================================================
check: $(BIN_DEBUG)
	@echo "  CHECK  Sending test query to localhost (requires Valkey on :6379)"
	@./$(BIN_DEBUG) &                         \
	 DNS_PID=$$!;                              \
	 sleep 1;                                  \
	 dig @127.0.0.1 -p 5353 example.local A   \
	     +time=2 +tries=1 +short;             \
	 kill $$DNS_PID 2>/dev/null || true

# =============================================================================
# Clean
# =============================================================================
clean:
	@echo "  CLEAN"
	rm -f $(BIN) $(BIN_DEBUG) $(SIG_GPG) $(SIG_OSSL)
	@echo "  done"

# =============================================================================
# Help
# =============================================================================
help:
	@echo ""
	@echo "dns_server build system"
	@echo ""
	@echo "  make              Production build: optimised, stripped, GPG-signed"
	@echo "  make debug        Debug build: ASan/UBSan, full symbols, not stripped"
	@echo "  make sign         (Re-)sign the existing production binary with GPG"
	@echo "  make sign-openssl Sign with OpenSSL Ed25519 key (keys/codesign.key.pem)"
	@echo "  make verify       Verify GPG and/or OpenSSL signatures"
	@echo "  make install      Install binary + signature to \$$(DESTDIR)\$$(PREFIX)/bin"
	@echo "  make uninstall    Remove installed files"
	@echo "  make check        Quick smoke-test (needs Valkey)"
	@echo "  make clean        Remove build artefacts"
	@echo "  make gen-signing-key  Generate OpenSSL Ed25519 code-signing key pair"
	@echo "  make help         This message"
	@echo ""
	@echo "Override variables:"
	@echo "  CC=clang          Use Clang instead of GCC"
	@echo "  GPG_KEY=<id>      GPG key fingerprint or email to sign with"
	@echo "  OSSL_INC=<path>   OpenSSL include directory"
	@echo "  OSSL_LIB=<path>   OpenSSL library directory"
	@echo "  PREFIX=<path>     Install prefix (default: /usr/local)"
	@echo "  DESTDIR=<path>    Staging directory for packagers"
	@echo ""
	@echo "Example — build for packaging:"
	@echo "  make prod GPG_KEY=ops@example.com DESTDIR=\$$(pwd)/pkg PREFIX=/usr"
	@echo ""
