# =============================================================================
# dns_server — Authoritative DNS Server
# =============================================================================
#
# Targets:
#   make              → production build (optimised, stripped, signed)
#   make prod         → same as above
#   make debug        → debug build (symbols, sanitisers, no stripping)
#   make clean        → remove all build artefacts
#   make sign         → (re-)sign an already-built production binary
#   make verify       → verify signature on production binary
#   make install      → install production binary + signature to $(DESTDIR)$(PREFIX)/bin
#   make uninstall    → remove installed files
#   make check        → quick smoke-test (requires a running Valkey on 127.0.0.1:6379)
#
# Signing:
#   The production binary is signed with GPG (detached, armoured .asc signature).
#   To use your own key:
#       make prod GPG_KEY=<fingerprint-or-email>
#   To sign with a dedicated code-signing key generated by this Makefile:
#       make gen-signing-key     → create keys/codesign.{key,crt} (Ed25519, self-signed)
#       make                     → build + GPG-sign with $(GPG_KEY)
#   The OpenSSL raw-signature target (sign-openssl) produces a SHA-256/Ed25519
#   signature file alongside the GPG .asc, so deployments that cannot use GPG
#   can verify with openssl dgst.
#
# =============================================================================

# ── Source & output names ────────────────────────────────────────────────────
# libdnswire (dns_wire.c/h) is the single shared wire-format implementation
# (migration Step 1); every binary compiles it in.
WIRE_SRC   := dns_wire.c
# Shared privilege-drop / chroot / seccomp sandbox (sandbox.c/h); linked by the
# daemons that confine themselves after binding (dnsd, resolverd).
SANDBOX_SRC := sandbox.c
SRC        := dns_server.c $(WIRE_SRC) $(SANDBOX_SRC)
BIN        := dns_server
BIN_DEBUG  := dns_server_debug
# Port the test harness runs dnsd's DNS listener on. Default 5356 avoids the
# mDNS port 5353, which collides with a desktop avahi-daemon (dig would hit
# avahi instead of dnsd). Override with `make TPORT=5353 check-*` if needed.
TPORT      ?= 5356
SIG_GPG    := $(BIN).asc
SIG_OSSL   := $(BIN).sig
OSSL_PUBKEY := keys/codesign.pub.pem

# ── Install paths ────────────────────────────────────────────────────────────
PREFIX     ?= /usr/local
DESTDIR    ?=
BINDIR      = $(DESTDIR)$(PREFIX)/bin
SIGDIR      = $(DESTDIR)$(PREFIX)/share/dns_server/signatures

# ── Compiler ─────────────────────────────────────────────────────────────────
CC         ?= gcc
CSTD        = -std=c99 -D_GNU_SOURCE

# ── OpenSSL paths (override on the command line if non-standard) ─────────────
#   Example: make OSSL_INC=/opt/openssl/include OSSL_LIB=/opt/openssl/lib
# Defaults are derived via pkg-config so they are correct per-platform
# (Debian multiarch, Fedora /usr/lib64, Homebrew, …). A world-writable or
# bogus default is a build-integrity risk — the sanity check below fails the
# build with a clear message rather than searching the wrong place.
OSSL_INC   ?= $(shell pkg-config --variable=includedir openssl 2>/dev/null || echo /usr/include)
OSSL_LIB   ?= $(shell pkg-config --variable=libdir openssl 2>/dev/null || echo /usr/lib)

# ── Signing ──────────────────────────────────────────────────────────────────
# GPG key fingerprint / email to sign with.
# Defaults to the first secret key in the keyring; set explicitly for CI.
GPG_KEY    ?=
GPG_SIGN    = gpg --batch --yes --armor --detach-sign
ifneq ($(strip $(GPG_KEY)),)
GPG_SIGN   += --local-user "$(GPG_KEY)"
endif

# OpenSSL Ed25519 key for the secondary raw-signature (optional).
OSSL_SIGN_KEY ?= keys/codesign.key.pem

# ── Common compile flags ─────────────────────────────────────────────────────
# EXTRA_WARN is appended last so CI can promote the curated set to errors with
# `make ... EXTRA_WARN=-Werror` without dropping the intentional -Wno-* flags
# (CLAUDE.md: "promote the current warning set", keep the legacy suppressions).
WARN       := -Wall -Wextra -Wformat=2 -Wformat-overflow=2 \
              -Wnull-dereference -Wstack-protector \
              -Wno-unused-parameter -Wno-missing-field-initializers \
              -Wno-implicit-fallthrough $(EXTRA_WARN)

INCLUDES   := -I$(OSSL_INC)
LIBS       := -L$(OSSL_LIB) -lssl -lcrypto -lpthread -Wl,-rpath,$(OSSL_LIB)

# libseccomp (optional): dnsd and resolverd install a syscall filter when the
# dev package is present (-DHAVE_SECCOMP). Without it they still build, just
# without the seccomp layer (priv-drop + chroot/mountns still apply). Detected
# via pkg-config; $(BIN)/$(BIN_DEBUG) and resolverd/resolverd_debug link it.
# CI installs libseccomp-dev so the filter is built+tested there too.
SECCOMP_CFLAGS := $(shell pkg-config --exists libseccomp 2>/dev/null && echo -DHAVE_SECCOMP $$(pkg-config --cflags libseccomp))
SECCOMP_LIBS   := $(shell pkg-config --exists libseccomp 2>/dev/null && pkg-config --libs libseccomp)

# ── Production flags ─────────────────────────────────────────────────────────
#   -O2          : safe optimisation level for a server daemon
#   -fstack-protector-strong : stack-smashing protection
#   -D_FORTIFY_SOURCE=2      : glibc buffer-overflow detection
#   -fPIE / -pie             : position-independent executable (ASLR)
#   -Wl,-z,relro,-z,now      : read-only relocations, immediate binding
PROD_FLAGS := -O2 \
              -fstack-protector-strong \
              -D_FORTIFY_SOURCE=2 \
              -fPIE \
              -pie -Wl,-z,relro,-z,now

# ── Debug flags ──────────────────────────────────────────────────────────────
#   -Og          : optimise for debugging (readable code, no inlining)
#   -g3 -ggdb    : maximum DWARF info
#   -fsanitize   : AddressSanitizer + UBSanitizer
#   -fno-omit-frame-pointer : accurate stack traces under ASan
DEBUG_FLAGS := -Og -g3 -ggdb \
               -fsanitize=address,undefined \
               -fno-omit-frame-pointer \
               -DDEBUG

# ── Build version string (embedded via -DBUILD_VERSION) ─────────────────────
GIT_SHA    := $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_DATE := $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
VERSION_FLAGS := -DBUILD_VERSION='"$(GIT_SHA)"' -DBUILD_DATE='"$(BUILD_DATE)"'

# =============================================================================
# Phony targets
# =============================================================================
.PHONY: all prod debug clean sign sign-openssl verify install uninstall \
        check check-cds check-catalog check-resolverd check-resolverd-cache check-resolverd-cookie check-dnssec check-dnssec-live check-axfr check-ixfr check-ixfr-client check-xfr-client check-xfr-refresh check-xfr-tsig check-dot-mtls check-ddns-acl check-ddns-sweeper check-notify check-ptr check-role check-forwarder check-lb check-lb-health check-wire fuzz-wire gen-signing-key help ossl-sanity \
        certd certd_debug mdnsd mdnsd_debug apid apid_debug resolverd resolverd_debug

# Fail fast, with an actionable message, if the OpenSSL paths are wrong —
# instead of a wall of confusing compiler/linker errors.
ossl-sanity:
	@test -f "$(OSSL_INC)/openssl/ssl.h" || { \
	    echo "error: OpenSSL headers not found at $(OSSL_INC)/openssl/ssl.h."; \
	    echo "       Install the OpenSSL 3.x dev package (openssl-devel /"; \
	    echo "       libssl-dev) or pass OSSL_INC=<include-dir>."; \
	    exit 1; }
	@ls "$(OSSL_LIB)"/libcrypto.* >/dev/null 2>&1 || { \
	    echo "error: OpenSSL libraries not found in $(OSSL_LIB)."; \
	    echo "       Install the OpenSSL 3.x dev package or pass OSSL_LIB=<lib-dir>."; \
	    exit 1; }

# Default → production
all: prod

# =============================================================================
# Production build
# =============================================================================
prod: $(BIN) sign

$(BIN): $(SRC) dns_wire.h sandbox.h | ossl-sanity
	@echo "  CC [PROD]  $@"
	$(CC) $(CSTD) $(WARN) $(PROD_FLAGS) $(VERSION_FLAGS) $(SECCOMP_CFLAGS) \
	      $(INCLUDES) -o $@ $(filter %.c,$^) $(LIBS) $(SECCOMP_LIBS)
	@echo "  STRIP      $@"
	strip --strip-unneeded \
	      --remove-section=.comment \
	      --remove-section=.note \
	      $@
	@echo "  SIZE       $@"
	@size $@
	@echo ""
	@echo "  Production binary: $@ (stripped, hardened)"

# =============================================================================
# Debug build
# =============================================================================
debug: $(BIN_DEBUG)

$(BIN_DEBUG): $(SRC) dns_wire.h sandbox.h | ossl-sanity
	@echo "  CC [DEBUG] $@"
	$(CC) $(CSTD) $(WARN) $(DEBUG_FLAGS) $(VERSION_FLAGS) $(SECCOMP_CFLAGS) \
	      $(INCLUDES) -o $@ $(filter %.c,$^) $(LIBS) $(SECCOMP_LIBS)

# =============================================================================
# certd — certificate manager sidecar (ACME + EST; migration Step 2)
# =============================================================================
certd: certd.c $(WIRE_SRC) dns_wire.h | ossl-sanity
	@echo "  CC [PROD]  $@"
	$(CC) $(CSTD) $(WARN) $(PROD_FLAGS) $(VERSION_FLAGS) \
	      $(INCLUDES) -o $@ $(filter %.c,$^) $(LIBS)
	strip --strip-unneeded $@

certd_debug: certd.c $(WIRE_SRC) dns_wire.h | ossl-sanity
	@echo "  CC [DEBUG] $@"
	$(CC) $(CSTD) $(WARN) $(DEBUG_FLAGS) $(VERSION_FLAGS) \
	      $(INCLUDES) -o $@ $(filter %.c,$^) $(LIBS)

# =============================================================================
# mdnsd — mDNS / DNS-SD responder (link-local; migration Step 3)
# =============================================================================
mdnsd: mdnsd.c $(WIRE_SRC) dns_wire.h | ossl-sanity
	@echo "  CC [PROD]  $@"
	$(CC) $(CSTD) $(WARN) $(PROD_FLAGS) $(VERSION_FLAGS) \
	      $(INCLUDES) -o $@ $(filter %.c,$^) $(LIBS)
	strip --strip-unneeded $@

mdnsd_debug: mdnsd.c $(WIRE_SRC) dns_wire.h | ossl-sanity
	@echo "  CC [DEBUG] $@"
	$(CC) $(CSTD) $(WARN) $(DEBUG_FLAGS) $(VERSION_FLAGS) \
	      $(INCLUDES) -o $@ $(filter %.c,$^) $(LIBS)
	@echo ""
	@echo "  Debug binary: $@  (ASan/UBSan enabled — do NOT use in production)"

# =============================================================================
# apid — HTTP/HTTPS front for DoH + management (migration Step 4)
# =============================================================================
apid: apid.c $(WIRE_SRC) dns_wire.h | ossl-sanity
	@echo "  CC [PROD]  $@"
	$(CC) $(CSTD) $(WARN) $(PROD_FLAGS) $(VERSION_FLAGS) \
	      $(INCLUDES) -o $@ $(filter %.c,$^) $(LIBS)
	strip --strip-unneeded $@

apid_debug: apid.c $(WIRE_SRC) dns_wire.h | ossl-sanity
	@echo "  CC [DEBUG] $@"
	$(CC) $(CSTD) $(WARN) $(DEBUG_FLAGS) $(VERSION_FLAGS) \
	      $(INCLUDES) -o $@ $(filter %.c,$^) $(LIBS)
	@echo ""
	@echo "  Debug binary: $@  (ASan/UBSan enabled — do NOT use in production)"
	@echo "  Run as:  ASAN_OPTIONS=detect_leaks=1 ./$@"

# =============================================================================
# resolverd — recursive/forwarding resolver + cache + DNSSEC validation
# (the recursive role; formerly dns_client.c). Distinct daemon from dnsd.
# -Wno-misleading-indentation: resolverd.c is clang-format-conformant but its
# dense one-statement-heavy style trips gcc's -Wmisleading-indentation heuristic;
# suppress just that one warning here (as the unit-test targets already do) to
# keep the -Werror build green. The rest of the curated WARN set still applies.
# =============================================================================
resolverd: resolverd.c $(WIRE_SRC) $(SANDBOX_SRC) dns_wire.h sandbox.h | ossl-sanity
	@echo "  CC [PROD]  $@"
	$(CC) $(CSTD) $(WARN) -Wno-misleading-indentation $(PROD_FLAGS) $(VERSION_FLAGS) \
	      $(SECCOMP_CFLAGS) $(INCLUDES) -o $@ $(filter %.c,$^) $(LIBS) $(SECCOMP_LIBS)
	strip --strip-unneeded $@

resolverd_debug: resolverd.c $(WIRE_SRC) $(SANDBOX_SRC) dns_wire.h sandbox.h | ossl-sanity
	@echo "  CC [DEBUG] $@"
	$(CC) $(CSTD) $(WARN) -Wno-misleading-indentation $(DEBUG_FLAGS) $(VERSION_FLAGS) \
	      $(SECCOMP_CFLAGS) $(INCLUDES) -o $@ $(filter %.c,$^) $(LIBS) $(SECCOMP_LIBS)
	@echo ""
	@echo "  Debug binary: $@  (ASan/UBSan enabled — do NOT use in production)"
	@echo "  Run as:  ASAN_OPTIONS=detect_leaks=1 ./$@"

# =============================================================================
# Signing
# =============================================================================

# GPG detached armoured signature
sign: $(BIN)
	@echo "  SIGN [GPG] $(BIN) → $(SIG_GPG)"
	$(GPG_SIGN) --output $(SIG_GPG) $(BIN)
	@echo "  GPG signature written: $(SIG_GPG)"
	@echo ""
	@gpg --batch --verify $(SIG_GPG) $(BIN) && \
	    echo "  ✓ Signature verified OK" || \
	    (echo "  ✗ Signature verification FAILED"; exit 1)

# OpenSSL Ed25519 raw-signature (secondary, non-GPG environments)
sign-openssl: $(BIN) $(OSSL_SIGN_KEY)
	@echo "  SIGN [OSSL] $(BIN) → $(SIG_OSSL)"
	openssl dgst -sha256 -sign $(OSSL_SIGN_KEY) \
	        -out $(SIG_OSSL) $(BIN)
	@echo "  OpenSSL signature written: $(SIG_OSSL)"
	@echo "  Verify with:"
	@echo "    openssl dgst -sha256 -verify $(OSSL_PUBKEY) -signature $(SIG_OSSL) $(BIN)"

# =============================================================================
# Verification
# =============================================================================
verify: $(BIN) $(SIG_GPG)
	@echo "  VERIFY [GPG] $(SIG_GPG)"
	@gpg --batch --verify $(SIG_GPG) $(BIN) && \
	    echo "  ✓  GPG signature is valid" || \
	    (echo "  ✗  GPG signature is INVALID or key not trusted"; exit 1)
	@if [ -f $(SIG_OSSL) ] && [ -f $(OSSL_PUBKEY) ]; then \
	    echo "  VERIFY [OSSL] $(SIG_OSSL)"; \
	    openssl dgst -sha256 -verify $(OSSL_PUBKEY) \
	            -signature $(SIG_OSSL) $(BIN) && \
	        echo "  ✓  OpenSSL signature is valid" || \
	        echo "  ✗  OpenSSL signature is INVALID"; \
	fi

# =============================================================================
# Code-signing key generation (one-time setup)
# =============================================================================
gen-signing-key:
	@mkdir -p keys
	@echo "  GEN  Ed25519 code-signing key pair → keys/codesign.{key,pub}.pem"
	openssl genpkey -algorithm ed25519 -out keys/codesign.key.pem
	openssl pkey -in keys/codesign.key.pem -pubout -out keys/codesign.pub.pem
	@echo ""
	@echo "  Self-signed certificate (for reference / TLSA/DANE use):"
	openssl req -new -x509 -days 3650 \
	        -key keys/codesign.key.pem \
	        -out keys/codesign.crt \
	        -subj "/CN=dns_server-codesign/O=Local/C=US"
	@chmod 600 keys/codesign.key.pem
	@echo ""
	@echo "  ✓  Keys generated. Keep keys/codesign.key.pem secret."
	@echo "     Distribute keys/codesign.pub.pem to verifiers."
	@echo ""
	@echo "  To generate a GPG code-signing key:"
	@echo "    gpg --batch --gen-key <<EOF"
	@echo "    %no-protection"
	@echo "    Key-Type: ed25519"
	@echo "    Key-Usage: sign"
	@echo "    Name-Real: dns_server codesign"
	@echo "    Name-Email: codesign@example.local"
	@echo "    Expire-Date: 2y"
	@echo "    %commit"
	@echo "    EOF"
	@echo "  Then: make prod GPG_KEY=codesign@example.local"

# =============================================================================
# Install
# =============================================================================
install: $(BIN) $(SIG_GPG)
	@echo "  INSTALL $(BIN) → $(BINDIR)/$(BIN)"
	install -d $(BINDIR)
	install -m 0755 $(BIN) $(BINDIR)/$(BIN)
	@echo "  INSTALL $(SIG_GPG) → $(SIGDIR)/$(SIG_GPG)"
	install -d $(SIGDIR)
	install -m 0644 $(SIG_GPG) $(SIGDIR)/$(SIG_GPG)
	@if [ -f $(SIG_OSSL) ]; then \
	    echo "  INSTALL $(SIG_OSSL) → $(SIGDIR)/$(SIG_OSSL)"; \
	    install -m 0644 $(SIG_OSSL) $(SIGDIR)/$(SIG_OSSL); \
	fi
	@echo ""
	@echo "  ✓  Installed. Verify on target with:"
	@echo "     gpg --verify $(SIGDIR)/$(SIG_GPG) $(BINDIR)/$(BIN)"

uninstall:
	@echo "  REMOVE $(BINDIR)/$(BIN)"
	rm -f $(BINDIR)/$(BIN)
	@echo "  REMOVE $(SIGDIR)/$(SIG_GPG) $(SIGDIR)/$(SIG_OSSL)"
	rm -f $(SIGDIR)/$(SIG_GPG) $(SIGDIR)/$(SIG_OSSL)
	@rmdir --ignore-fail-on-non-empty $(SIGDIR) 2>/dev/null || true

# =============================================================================
# Unit tests
# =============================================================================
# DNSSEC known-answer + negative tests.
# Includes resolverd.c with -DUNIT_TEST, so it inherits that file's (dense,
# pre-clang-format) style — suppress the indentation warning for now.
check-dnssec: tests/test_dnssec_verify.c tests/test_rollover.c resolverd.c $(WIRE_SRC) $(SANDBOX_SRC) dns_wire.h sandbox.h | ossl-sanity
	@echo "  CC [TEST]  tests/test_dnssec_verify"
	$(CC) $(CSTD) $(WARN) -Wno-misleading-indentation $(DEBUG_FLAGS) \
	      $(INCLUDES) -I. -o tests/test_dnssec_verify \
	      tests/test_dnssec_verify.c $(WIRE_SRC) $(SANDBOX_SRC) $(LIBS)
	./tests/test_dnssec_verify
	@echo "  CC [TEST]  tests/test_rollover"
	$(CC) $(CSTD) $(WARN) -Wno-misleading-indentation -Wno-unused-function \
	      $(DEBUG_FLAGS) \
	      $(INCLUDES) -I. -o tests/test_rollover \
	      tests/test_rollover.c $(WIRE_SRC) $(SANDBOX_SRC) $(LIBS)
	./tests/test_rollover

# name_from_wire compression-handling tests.
# -Wno-unused-function: -DUNIT_TEST compiles out resolverd.c's main(), which
# is the only caller of some helpers.
check-wire: tests/test_name_from_wire.c resolverd.c $(WIRE_SRC) $(SANDBOX_SRC) dns_wire.h sandbox.h | ossl-sanity
	@echo "  CC [TEST]  tests/test_name_from_wire"
	$(CC) $(CSTD) $(WARN) -Wno-misleading-indentation -Wno-unused-function \
	      $(DEBUG_FLAGS) \
	      $(INCLUDES) -I. -o tests/test_name_from_wire \
	      tests/test_name_from_wire.c $(WIRE_SRC) $(SANDBOX_SRC) $(LIBS)
	./tests/test_name_from_wire

# libFuzzer smoke target for the name parser (requires clang).
fuzz-wire: fuzz/fuzz_name_from_wire.c $(WIRE_SRC) dns_wire.h
	@echo "  CC [FUZZ]  fuzz_name_from_wire (clang, ASan+UBSan+libFuzzer)"
	clang -g -O1 -fsanitize=fuzzer,address,undefined -I. \
	      -o fuzz/fuzz_name_from_wire \
	      fuzz/fuzz_name_from_wire.c $(WIRE_SRC)
	mkdir -p fuzz/corpus
	./fuzz/fuzz_name_from_wire -max_total_time=60 fuzz/corpus

# =============================================================================
# Smoke test
# =============================================================================
check: $(BIN_DEBUG)
	@echo "  CHECK  Sending test query to localhost (requires Valkey on :6379)"
	@LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) &                         \
	 DNS_PID=$$!;                              \
	 sleep 1;                                  \
	 dig @127.0.0.1 -p $(TPORT) example.local A   \
	     +time=2 +tries=1 +short;             \
	 kill $$DNS_PID 2>/dev/null || true

# Live DNSSEC regression (guards the EDNS DO-bit parse, RFC 6891 §6.1.3). A
# query with the DO bit set must return RRSIGs; the same query WITHOUT DO must
# not. A misparsed DO bit silently strips DNSSEC from every live response while
# the unit tests (check-dnssec) still pass — so this exercises the live path.
# Needs Valkey + dig.
check-dnssec-live: $(BIN_DEBUG)
	@echo "  CHECK  live DNSSEC DO-bit honoured (requires Valkey + dig)"
	@ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_dolive.log 2>&1 & DNS=$$!;  \
	 sleep 1.5;                                                                        \
	 DO=0;                                                                             \
	 for i in 1 2 3 4 5 6 7 8 9 10 11 12; do                                           \
	   DO=$$(dig +dnssec +nocookie @127.0.0.1 -p $(TPORT) example.local SOA +time=2 +tries=1 | grep -c 'RRSIG'); \
	   if [ "$$DO" -ge 1 ]; then break; fi;                                            \
	   sleep 1;                                                                        \
	 done;                                                                             \
	 NODO=$$(dig +nodnssec +nocookie @127.0.0.1 -p $(TPORT) example.local SOA +time=2 +tries=1 | grep -c 'RRSIG'); \
	 kill $$DNS 2>/dev/null || true;                                                   \
	 echo "  +dnssec RRSIGs=$$DO   +nodnssec RRSIGs=$$NODO";                           \
	 test "$$DO" -ge 1  || { echo "  FAIL  DO=1 query returned no RRSIG (DO bit misparsed?)"; exit 1; }; \
	 test "$$NODO" -eq 0 || { echo "  FAIL  DO=0 query returned RRSIG (DNSSEC not gated on DO)"; exit 1; }; \
	 echo "  OK  RRSIGs returned iff the DO bit is set"

# Transfer TSIG (hidden-master plan Gap 4, RFC 8945). A secondary signs its AXFR
# request and verifies the master's chained-response MAC. Drive a TSIG-capable
# stub master (tests/axfr_master_tsig.py) that verifies the client's request
# signature (proving the client signs correctly) and signs the response. Assert:
# a correctly-signed transfer is applied; a response signed with the WRONG key is
# rejected; an UNSIGNED response (when a key is configured) is rejected — in both
# rejection cases the store stays empty. Needs Valkey + dig + python3.
check-xfr-tsig: $(BIN_DEBUG)
	@echo "  CHECK  transfer TSIG sign+verify (RFC 8945) — requires Valkey + dig + python3"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 command -v python3 >/dev/null || { echo "  SKIP  no python3 on PATH"; exit 0; };  \
	 Z=xfrtsig.test; P=5390; B64=$$(printf '0123456789abcdef0123456789abcdef' | base64); \
	 SAVE_TS=$$($$VC get config:tsig_secret_b64); SAVE_KN=$$($$VC get config:tsig_key_name); \
	 SAVE_ROLE=$$($$VC get config:zone_role); SAVE_PH=$$($$VC get config:primary_host);\
	 SAVE_PP=$$($$VC get config:primary_port); SAVE_PT=$$($$VC get config:primary_tls);\
	 $$VC set config:tsig_secret_b64 "$$B64" >/dev/null;                               \
	 $$VC set config:tsig_key_name tsig-key >/dev/null;                                \
	 $$VC set zone_table:$$Z "ns1.$$Z|hostmaster.$$Z|1|3600|900|604800|300|127.0.0.1|" >/dev/null; \
	 $$VC set config:zone_role secondary >/dev/null;                                   \
	 $$VC set config:primary_host 127.0.0.1 >/dev/null;                                \
	 $$VC set config:primary_port $$P >/dev/null;                                      \
	 $$VC set config:primary_tls 0 >/dev/null;                                         \
	 RES="";                                                                           \
	 for MODE in ok badresp unsigned; do                                              \
	   for k in $$($$VC --scan --pattern "zone:$$Z:*"); do $$VC del "$$k" >/dev/null; done; \
	   python3 tests/axfr_master_tsig.py 127.0.0.1 $$P $$Z "$$B64" $$MODE >/tmp/xtsig_m.log 2>&1 & M=$$!; \
	   for w in $$(seq 1 50); do ss -ltn 2>/dev/null | grep -q ":$$P " && break; sleep 0.1; done; \
	   ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/xtsig_s.log 2>&1 & DNS=$$!;    \
	   sleep 2.2;                                                                       \
	   W=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) www.$$Z A +time=2 +tries=1);        \
	   kill $$DNS $$M 2>/dev/null || true; sleep 0.3;                                   \
	   RES="$$RES $$MODE=[$$W]";                                                         \
	   eval "R_$$MODE=\"$$W\"";                                                          \
	 done;                                                                             \
	 $$VC del zone_table:$$Z config:primary_host config:primary_port config:primary_tls config:zone:$$Z:serial config:tsig_key_name >/dev/null; \
	 for k in $$($$VC --scan --pattern "zone:$$Z:*") $$($$VC --scan --pattern "dnssec:$$Z:*"); do $$VC del "$$k" >/dev/null; done; \
	 if [ -n "$$SAVE_TS" ]; then $$VC set config:tsig_secret_b64 "$$SAVE_TS" >/dev/null; else $$VC del config:tsig_secret_b64 >/dev/null; fi; \
	 if [ -n "$$SAVE_KN" ]; then $$VC set config:tsig_key_name "$$SAVE_KN" >/dev/null; fi; \
	 if [ -n "$$SAVE_ROLE" ]; then $$VC set config:zone_role "$$SAVE_ROLE" >/dev/null; else $$VC del config:zone_role >/dev/null; fi; \
	 if [ -n "$$SAVE_PH" ]; then $$VC set config:primary_host "$$SAVE_PH" >/dev/null; fi; \
	 if [ -n "$$SAVE_PP" ]; then $$VC set config:primary_port "$$SAVE_PP" >/dev/null; fi; \
	 if [ -n "$$SAVE_PT" ]; then $$VC set config:primary_tls "$$SAVE_PT" >/dev/null; fi; \
	 echo "  results:$$RES"; \
	 test "$$R_ok" = "10.20.0.1" || { echo "  FAIL  valid TSIG transfer not applied"; exit 1; }; \
	 test -z "$$R_badresp" || { echo "  FAIL  response with wrong key was NOT rejected"; exit 1; }; \
	 test -z "$$R_unsigned" || { echo "  FAIL  unsigned response was NOT rejected (TSIG required)"; exit 1; }; \
	 echo "  OK  valid TSIG applied; wrong-key + unsigned responses rejected"

# Secondary zone maintenance: NOTIFY-triggered refresh + SOA expire (hidden-
# master plan Gap 6/5). A secondary re-pulls a zone immediately on a NOTIFY from
# its master and, if it cannot refresh within the SOA expire, stops answering
# authoritatively (SERVFAIL). Drive a stub master whose serial/records can be
# changed mid-run via a control file; assert: (1) a NOTIFY makes the secondary
# pick up the new serial + a new record; (2) after the master dies and expire
# elapses, the zone SERVFAILs. Needs Valkey + dig + python3.
check-xfr-refresh: $(BIN_DEBUG)
	@echo "  CHECK  secondary refresh: NOTIFY re-pull + SOA expire (Valkey + dig + python3)"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 command -v python3 >/dev/null || { echo "  SKIP  no python3 on PATH"; exit 0; };  \
	 Z=xfrpull.test; P=5389; CTL=$$(mktemp);                                           \
	 echo 100 > $$CTL;                                                                 \
	 SAVE_ROLE=$$($$VC get config:zone_role); SAVE_PH=$$($$VC get config:primary_host);\
	 SAVE_PP=$$($$VC get config:primary_port); SAVE_PT=$$($$VC get config:primary_tls);\
	 python3 tests/axfr_master.py 127.0.0.1 $$P $$Z $$CTL >/tmp/axfr_master_r.log 2>&1 & M=$$!; \
	 $$VC set zone_table:$$Z "ns1.$$Z|hostmaster.$$Z|1|2|1|4|300|127.0.0.1|" >/dev/null; \
	 for k in $$($$VC --scan --pattern "zone:$$Z:*"); do $$VC del "$$k" >/dev/null; done; \
	 $$VC set config:zone_role secondary >/dev/null;                                   \
	 $$VC set config:primary_host 127.0.0.1 >/dev/null;                                \
	 $$VC set config:primary_port $$P >/dev/null;                                      \
	 $$VC set config:primary_tls 0 >/dev/null;                                         \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_ref.log 2>&1 & DNS=$$!;     \
	 sleep 2.5;                                                                        \
	 S1=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$Z SOA +time=2 +tries=1 | awk '{print $$3}'); \
	 N1=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) new.$$Z A +time=2 +tries=1);        \
	 printf '200\nnew\n' > $$CTL;                                                      \
	 dig +opcode=notify +nocookie @127.0.0.1 -p $(TPORT) $$Z SOA +time=2 +tries=1 >/dev/null 2>&1; \
	 sleep 1.5;                                                                        \
	 S2=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$Z SOA +time=2 +tries=1 | awk '{print $$3}'); \
	 N2=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) new.$$Z A +time=2 +tries=1);        \
	 kill $$M 2>/dev/null || true; sleep 6;                                            \
	 EXP=$$(dig +nocookie @127.0.0.1 -p $(TPORT) $$Z SOA +time=2 +tries=1 | grep -c 'status: SERVFAIL'); \
	 kill $$DNS 2>/dev/null || true;                                                   \
	 $$VC del zone_table:$$Z config:primary_host config:primary_port config:primary_tls config:zone:$$Z:serial >/dev/null; \
	 for k in $$($$VC --scan --pattern "zone:$$Z:*") $$($$VC --scan --pattern "dnssec:$$Z:*"); do $$VC del "$$k" >/dev/null; done; \
	 if [ -n "$$SAVE_ROLE" ]; then $$VC set config:zone_role "$$SAVE_ROLE" >/dev/null; else $$VC del config:zone_role >/dev/null; fi; \
	 if [ -n "$$SAVE_PH" ]; then $$VC set config:primary_host "$$SAVE_PH" >/dev/null; fi; \
	 if [ -n "$$SAVE_PP" ]; then $$VC set config:primary_port "$$SAVE_PP" >/dev/null; fi; \
	 if [ -n "$$SAVE_PT" ]; then $$VC set config:primary_tls "$$SAVE_PT" >/dev/null; fi; \
	 rm -f $$CTL;                                                                      \
	 echo "  startup: serial=$$S1 new=[$$N1] | after NOTIFY: serial=$$S2 new=[$$N2] | post-expire SERVFAIL=$$EXP"; \
	 test "$$S1" = "100" || { echo "  FAIL  startup pull serial ($$S1 != 100)"; exit 1; }; \
	 test -z "$$N1" || { echo "  FAIL  new record present before it was added"; exit 1; }; \
	 test "$$S2" = "200" || { echo "  FAIL  NOTIFY did not trigger refresh ($$S2 != 200)"; exit 1; }; \
	 test "$$N2" = "10.10.0.9" || { echo "  FAIL  NOTIFY refresh did not pick up the new record"; exit 1; }; \
	 test "$$EXP" -ge 1 || { echo "  FAIL  zone past SOA expire did not SERVFAIL"; exit 1; }; \
	 echo "  OK  NOTIFY re-pulls (new serial+record); zone SERVFAILs past expire"

# Zone transfer CLIENT (hidden-master plan Gap 3). A secondary pulls each zone
# from its master at startup. Drive a stub master (tests/axfr_master.py) that
# serves one throwaway zone over plain TCP, run dnsd as a secondary pointed at
# it, and assert the secondary now serves the transferred records (multi-IP A,
# TXT, CNAME) with the master's serial — and that a zone the stub does NOT serve
# (example.local) is left untouched (a failed pull must not wipe the store).
# Needs Valkey + dig + python3; restores config afterward.
check-xfr-client: $(BIN_DEBUG)
	@echo "  CHECK  secondary AXFR pull from master (requires Valkey + dig + python3)"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 command -v python3 >/dev/null || { echo "  SKIP  no python3 on PATH"; exit 0; };  \
	 Z=xfrpull.test; P=5388;                                                           \
	 SAVE_ROLE=$$($$VC get config:zone_role); SAVE_PH=$$($$VC get config:primary_host);\
	 SAVE_PP=$$($$VC get config:primary_port); SAVE_PT=$$($$VC get config:primary_tls);\
	 python3 tests/axfr_master.py 127.0.0.1 $$P $$Z >/tmp/axfr_master.log 2>&1 & M=$$!;\
	 $$VC set zone_table:$$Z "ns1.$$Z|hostmaster.$$Z|1|3600|900|604800|300|127.0.0.1|" >/dev/null; \
	 for k in $$($$VC --scan --pattern "zone:$$Z:*"); do $$VC del "$$k" >/dev/null; done; \
	 $$VC set config:zone_role secondary >/dev/null;                                   \
	 $$VC set config:primary_host 127.0.0.1 >/dev/null;                                \
	 $$VC set config:primary_port $$P >/dev/null;                                      \
	 $$VC set config:primary_tls 0 >/dev/null;                                         \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_sec.log 2>&1 & DNS=$$!;     \
	 sleep 2.5;                                                                        \
	 A=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) www.$$Z A +time=2 +tries=1 | sort | tr '\n' ' '); \
	 TX=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) info.$$Z TXT +time=2 +tries=1);     \
	 CN=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) alias.$$Z CNAME +time=2 +tries=1);  \
	 SOA=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$Z SOA +time=2 +tries=1 | awk '{print $$3}'); \
	 KEEP=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) www.example.local A +time=2 +tries=1); \
	 kill $$DNS $$M 2>/dev/null || true;                                               \
	 $$VC del zone_table:$$Z config:primary_host config:primary_port config:primary_tls config:zone:$$Z:serial >/dev/null; \
	 for k in $$($$VC --scan --pattern "zone:$$Z:*") $$($$VC --scan --pattern "dnssec:$$Z:*"); do $$VC del "$$k" >/dev/null; done; \
	 if [ -n "$$SAVE_ROLE" ]; then $$VC set config:zone_role "$$SAVE_ROLE" >/dev/null; else $$VC del config:zone_role >/dev/null; fi; \
	 if [ -n "$$SAVE_PH" ]; then $$VC set config:primary_host "$$SAVE_PH" >/dev/null; fi; \
	 if [ -n "$$SAVE_PP" ]; then $$VC set config:primary_port "$$SAVE_PP" >/dev/null; fi; \
	 if [ -n "$$SAVE_PT" ]; then $$VC set config:primary_tls "$$SAVE_PT" >/dev/null; fi; \
	 echo "  pulled: wwwA=[$$A] TXT=[$$TX] CNAME=[$$CN] serial=$$SOA | untouched: www.example.local=[$$KEEP]"; \
	 (echo "$$A" | grep -q "10.10.0.1") && (echo "$$A" | grep -q "10.10.0.2") || { echo "  FAIL  multi-IP A not transferred"; exit 1; }; \
	 test "$$TX" = '"hello-xfr"' || { echo "  FAIL  TXT not transferred"; exit 1; }; \
	 test "$$CN" = "www.$$Z." || { echo "  FAIL  CNAME not transferred"; exit 1; }; \
	 test "$$SOA" = "424242" || { echo "  FAIL  master serial not adopted (got $$SOA)"; exit 1; }; \
	 test "$$KEEP" = "192.168.1.10" || { echo "  FAIL  a failed pull clobbered example.local ($$KEEP)"; exit 1; }; \
	 echo "  OK  secondary pulled the zone (records + serial); other zones left intact"

# Secondary-role guards (hidden-master plan Gap 2/7/8). With
# config:zone_role=secondary the instance is a read-only replica: an RFC 2136
# UPDATE is refused with NOTAUTH (never applied locally), and a zone with no
# DNSSEC keys is served UNSIGNED rather than minting a divergent trust anchor
# (a primary, by contrast, generates the keys). Uses a throwaway zone + nsupdate;
# clears config:tsig_secret_b64 for the run. Needs Valkey + dig + nsupdate.
check-role: $(BIN_DEBUG)
	@echo "  CHECK  secondary role: UPDATE→NOTAUTH + no DNSSEC keygen (Valkey + dig + nsupdate)"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 command -v nsupdate >/dev/null || { echo "  SKIP  no nsupdate on PATH"; exit 0; };\
	 Z=roletest.local;                                                                 \
	 SAVE_TS=$$($$VC get config:tsig_secret_b64); SAVE_ROLE=$$($$VC get config:zone_role); \
	 $$VC del config:tsig_secret_b64 >/dev/null;                                       \
	 for k in $$($$VC --scan --pattern "dnssec:$$Z:*"); do $$VC del "$$k" >/dev/null; done; \
	 $$VC set zone_table:$$Z "ns1.$$Z|hostmaster.$$Z|3|3600|900|604800|300|127.0.0.1|" >/dev/null; \
	 $$VC set config:zone_role secondary >/dev/null;                                   \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_role1.log 2>&1 & DNS=$$!;   \
	 sleep 1.5;                                                                        \
	 NA=$$(printf 'server 127.0.0.1 $(TPORT)\nzone example.local\nupdate add r1.example.local 60 A 10.0.0.5\nsend\n' | nsupdate 2>&1 | grep -c -i notauth); \
	 R1=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) r1.example.local A +time=2 +tries=1);\
	 SEC_DK=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$Z DNSKEY +time=2 +tries=1 | grep -c '^25'); \
	 GUARD=$$(grep -c "ABSENT on a secondary" /tmp/dnsd_role1.log);                     \
	 kill $$DNS 2>/dev/null || true; sleep 0.3;                                        \
	 $$VC set config:zone_role primary >/dev/null;                                     \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_role2.log 2>&1 & DNS=$$!;   \
	 sleep 2;                                                                          \
	 PRI_DK=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$Z DNSKEY +time=2 +tries=1 | grep -c '^25'); \
	 kill $$DNS 2>/dev/null || true;                                                   \
	 $$VC del zone_table:$$Z >/dev/null;                                               \
	 for k in $$($$VC --scan --pattern "dnssec:$$Z:*"); do $$VC del "$$k" >/dev/null; done; \
	 if [ -n "$$SAVE_TS" ]; then $$VC set config:tsig_secret_b64 "$$SAVE_TS" >/dev/null; fi; \
	 if [ -n "$$SAVE_ROLE" ]; then $$VC set config:zone_role "$$SAVE_ROLE" >/dev/null; else $$VC del config:zone_role >/dev/null; fi; \
	 echo "  secondary: update_notauth=$$NA r1=[$$R1] dnskey=$$SEC_DK keyguard_log=$$GUARD | primary: dnskey=$$PRI_DK"; \
	 test "$$NA" -ge 1 || { echo "  FAIL  secondary did not refuse UPDATE with NOTAUTH"; exit 1; }; \
	 test -z "$$R1" || { echo "  FAIL  secondary applied a local UPDATE ($$R1)"; exit 1; }; \
	 test "$$SEC_DK" -eq 0 || { echo "  FAIL  secondary minted DNSKEY for a keyless zone"; exit 1; }; \
	 test "$$GUARD" -ge 1 || { echo "  FAIL  secondary key-guard did not log"; exit 1; }; \
	 test "$$PRI_DK" -ge 1 || { echo "  FAIL  primary did not generate DNSKEY (control)"; exit 1; }; \
	 echo "  OK  secondary refuses UPDATE + serves unsigned (no keygen); primary signs"

# DDNS suffix ACL + serial-churn skip (CLAUDE-discovery.md Gap 3). With
# config:ddns_allow_suffix set, RFC 2136 UPDATE may only touch names under that
# suffix (others REFUSED); and a lease refresh that re-stores the same address
# renews the TTL without bumping the SOA serial (only a real change does). Uses
# nsupdate; clears config:tsig_secret_b64 for the run so the test exercises the
# ACL/churn logic without TSIG plumbing (both are TSIG-independent). Needs
# Valkey + dig + nsupdate; restores config afterward.
check-ddns-acl: $(BIN_DEBUG)
	@echo "  CHECK  DDNS suffix ACL + serial-churn skip (requires Valkey + dig + nsupdate)"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 command -v nsupdate >/dev/null || { echo "  SKIP  no nsupdate on PATH"; exit 0; };\
	 Z=example.local; FQDN=web1.dyn.$$Z;                                               \
	 SAVE_TS=$$($$VC get config:tsig_secret_b64); SAVE_SX=$$($$VC get config:ddns_allow_suffix); \
	 $$VC del config:tsig_secret_b64 >/dev/null;                                       \
	 $$VC set config:ddns_allow_suffix ".dyn.$$Z" >/dev/null;                          \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_ddns.log 2>&1 & DNS=$$!;    \
	 sleep 1.5;                                                                        \
	 printf 'server 127.0.0.1 $(TPORT)\nzone %s\nupdate add %s 60 A 10.0.0.1\nsend\n' "$$Z" "$$FQDN" | nsupdate >/dev/null 2>&1; \
	 IN=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$FQDN A +time=2 +tries=1);         \
	 OUT=$$(printf 'server 127.0.0.1 $(TPORT)\nzone %s\nupdate add www.%s 60 A 6.6.6.6\nsend\n' "$$Z" "$$Z" | nsupdate 2>&1 | grep -c -i refused); \
	 WWW=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) www.$$Z A +time=2 +tries=1 | head -1); \
	 S1=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$Z SOA +time=2 +tries=1 | awk '{print $$3}'); \
	 printf 'server 127.0.0.1 $(TPORT)\nupdate add %s 60 A 10.0.0.1\nsend\n' "$$FQDN" | nsupdate >/dev/null 2>&1; \
	 S2=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$Z SOA +time=2 +tries=1 | awk '{print $$3}'); \
	 printf 'server 127.0.0.1 $(TPORT)\nupdate add %s 60 A 10.0.0.77\nsend\n' "$$FQDN" | nsupdate >/dev/null 2>&1; \
	 S3=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$Z SOA +time=2 +tries=1 | awk '{print $$3}'); \
	 kill $$DNS 2>/dev/null || true;                                                   \
	 $$VC del config:ddns_allow_suffix ddns:$$Z:A:$$FQDN >/dev/null;                   \
	 if [ -n "$$SAVE_TS" ]; then $$VC set config:tsig_secret_b64 "$$SAVE_TS" >/dev/null; fi; \
	 if [ -n "$$SAVE_SX" ]; then $$VC set config:ddns_allow_suffix "$$SAVE_SX" >/dev/null; fi; \
	 echo "  in-suffix A=[$$IN]  out-of-suffix refused=$$OUT www=[$$WWW]  serial S1=$$S1 S2=$$S2 S3=$$S3"; \
	 test "$$IN" = "10.0.0.1" || { echo "  FAIL  in-suffix UPDATE not applied"; exit 1; }; \
	 test "$$OUT" -ge 1 || { echo "  FAIL  out-of-suffix UPDATE was not REFUSED"; exit 1; }; \
	 test "$$WWW" != "6.6.6.6" || { echo "  FAIL  out-of-suffix UPDATE leaked into the zone"; exit 1; }; \
	 test -n "$$S1" -a "$$S1" = "$$S2" || { echo "  FAIL  refresh (same IP) churned the serial ($$S1 -> $$S2)"; exit 1; }; \
	 test "$$S3" != "$$S2" || { echo "  FAIL  changed IP did not bump the serial ($$S2 -> $$S3)"; exit 1; }; \
	 echo "  OK  suffix ACL enforced; refresh is serial-neutral; real change bumps serial"

# DDNS lease-expiry sweeper (CLAUDE-discovery.md Gap 2). A ddns:* lease expiring
# in Valkey is otherwise a silent delete (no serial bump / journal / NOTIFY).
# Seed a short-TTL A lease (EX) before starting dnsd so the sweeper snapshots it
# while alive; after it expires the sweeper must replay it as a real deletion:
# the SOA serial advances and an IXFR from the pre-expiry serial returns the
# 'D'. Reuses tests/ixfr_client.py. Needs Valkey + dig + python3.
check-ddns-sweeper: $(BIN_DEBUG)
	@echo "  CHECK  DDNS lease-expiry sweeper: silent expiry → serial bump + IXFR 'D' (Valkey + dig + python3)"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 command -v python3 >/dev/null || { echo "  SKIP  no python3 on PATH"; exit 0; };  \
	 Z=sweep.test; S0=200; HOST=host.$$Z; IP=10.1.2.3;                                 \
	 SAVE_AX=$$($$VC get config:axfr_allow); SAVE_SW=$$($$VC get config:ddns_sweep_secs); \
	 SAVE_TS=$$($$VC get config:tsig_secret_b64);                                      \
	 $$VC del config:tsig_secret_b64 >/dev/null;                                       \
	 $$VC set config:axfr_allow 127.0.0.1 >/dev/null;                                  \
	 $$VC set config:ddns_sweep_secs 1 >/dev/null;                                     \
	 $$VC set zone_table:$$Z "ns1.$$Z|hostmaster.$$Z|$$S0|3600|900|604800|300|127.0.0.1|" >/dev/null; \
	 $$VC set config:zone:$$Z:serial $$S0 >/dev/null;                                  \
	 $$VC del ixfr:$$Z:journal >/dev/null;                                             \
	 $$VC set ddns:$$Z:A:$$HOST $$IP EX 4 >/dev/null;                                  \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_sweep.log 2>&1 & DNS=$$!;   \
	 ALIVE=$$(sleep 1.5; dig +short +nocookie @127.0.0.1 -p $(TPORT) $$HOST A +time=2 +tries=1); \
	 sleep 6;                                                                          \
	 S1=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$Z SOA +time=2 +tries=1 | awk '{print $$3}'); \
	 GONE=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$HOST A +time=2 +tries=1);       \
	 INC=$$(python3 tests/ixfr_client.py 127.0.0.1 $(TPORT) $$Z $$S0 2>/dev/null);         \
	 kill $$DNS 2>/dev/null || true;                                                   \
	 $$VC del zone_table:$$Z config:zone:$$Z:serial ddns:$$Z:A:$$HOST ixfr:$$Z:journal >/dev/null; \
	 for k in $$($$VC --scan --pattern "dnssec:$$Z:*") $$($$VC --scan --pattern "zone:$$Z:*"); do $$VC del "$$k" >/dev/null; done; \
	 if [ -n "$$SAVE_AX" ]; then $$VC set config:axfr_allow "$$SAVE_AX" >/dev/null; else $$VC del config:axfr_allow >/dev/null; fi; \
	 if [ -n "$$SAVE_SW" ]; then $$VC set config:ddns_sweep_secs "$$SAVE_SW" >/dev/null; else $$VC del config:ddns_sweep_secs >/dev/null; fi; \
	 if [ -n "$$SAVE_TS" ]; then $$VC set config:tsig_secret_b64 "$$SAVE_TS" >/dev/null; fi; \
	 echo "  alive=[$$ALIVE] afterExpiry: serial=$$S1 host=[$$GONE]"; echo "$$INC" | sed 's/^/    /'; \
	 test "$$ALIVE" = "$$IP" || { echo "  FAIL  seeded lease was not served before expiry (got [$$ALIVE])"; exit 1; }; \
	 test "$$S1" = "201" || { echo "  FAIL  expiry did not bump the serial ($$S1 != 201) — sweeper silent?"; exit 1; }; \
	 test -z "$$GONE" || { echo "  FAIL  lease still served after expiry (got [$$GONE])"; exit 1; }; \
	 echo "$$INC" | grep -q "^MODE incremental" || { echo "  FAIL  pre-expiry serial did not yield an incremental diff"; exit 1; }; \
	 echo "$$INC" | grep -q "^DEL $$HOST A $$IP" || { echo "  FAIL  expiry not journalled as a delete (no DEL $$HOST)"; exit 1; }; \
	 echo "$$INC" | grep -q "^END 201" || { echo "  FAIL  incremental did not close at the post-expiry serial 201"; exit 1; }; \
	 echo "  OK  silent lease expiry replayed as a replicated delete (serial bump + IXFR 'D')"

# Master-side NOTIFY sender hardening (RFC 1996 §3.6 + RFC 8945). A stub
# secondary (tests/notify_secondary.py) verifies the NOTIFY's TSIG signature and
# withholds the ACK to the first NOTIFY, forcing a retransmit, then ACKs. A zone
# change is driven via the lease-expiry sweeper (notify path). Assert the master
# (1) TSIG-signs the NOTIFY, (2) retransmits when unacked, and (3) stops on ACK
# (well before the retry cap). Needs Valkey + python3.
check-notify: $(BIN_DEBUG)
	@echo "  CHECK  NOTIFY sender: TSIG-signed + retried until ACK (Valkey + python3)"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 command -v python3 >/dev/null || { echo "  SKIP  no python3 on PATH"; exit 0; };  \
	 Z=notify.test; SP=5396; S0=200;                                                   \
	 B64=$$(printf '0123456789abcdef0123456789abcdef' | base64);                       \
	 SAVE_TS=$$($$VC get config:tsig_secret_b64); SAVE_KN=$$($$VC get config:tsig_key_name); \
	 SAVE_SW=$$($$VC get config:ddns_sweep_secs);                                      \
	 $$VC set config:tsig_secret_b64 "$$B64" >/dev/null;                               \
	 $$VC set config:tsig_key_name tsig-key >/dev/null;                                \
	 $$VC set config:ddns_sweep_secs 1 >/dev/null;                                     \
	 $$VC set zone_table:$$Z "ns1.$$Z|hostmaster.$$Z|$$S0|3600|900|604800|300|127.0.0.1|127.0.0.1:$$SP" >/dev/null; \
	 $$VC set config:zone:$$Z:serial $$S0 >/dev/null;                                  \
	 $$VC set ddns:$$Z:A:host.$$Z 10.1.2.3 EX 4 >/dev/null;                            \
	 python3 tests/notify_secondary.py 127.0.0.1 $$SP $$Z "$$B64" 12 >/tmp/notify_sec.out 2>/tmp/notify_sec.err & STUB=$$!; \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_notify.log 2>&1 & DNS=$$!;  \
	 sleep 13;                                                                         \
	 kill $$DNS 2>/dev/null || true; wait $$STUB 2>/dev/null || true;                  \
	 OUT=$$(cat /tmp/notify_sec.out);                                                  \
	 $$VC del zone_table:$$Z config:zone:$$Z:serial ddns:$$Z:A:host.$$Z ixfr:$$Z:journal config:tsig_key_name >/dev/null; \
	 for k in $$($$VC --scan --pattern "dnssec:$$Z:*") $$($$VC --scan --pattern "zone:$$Z:*"); do $$VC del "$$k" >/dev/null; done; \
	 if [ -n "$$SAVE_TS" ]; then $$VC set config:tsig_secret_b64 "$$SAVE_TS" >/dev/null; else $$VC del config:tsig_secret_b64 >/dev/null; fi; \
	 if [ -n "$$SAVE_KN" ]; then $$VC set config:tsig_key_name "$$SAVE_KN" >/dev/null; fi; \
	 if [ -n "$$SAVE_SW" ]; then $$VC set config:ddns_sweep_secs "$$SAVE_SW" >/dev/null; else $$VC del config:ddns_sweep_secs >/dev/null; fi; \
	 CNT=$$(echo "$$OUT" | awk '/^COUNT/{print $$2}'); TS=$$(echo "$$OUT" | awk '/^TSIG/{print $$2}'); AK=$$(echo "$$OUT" | awk '/^ACKED/{print $$2}'); \
	 echo "  stub: count=$$CNT tsig=$$TS acked=$$AK";                                  \
	 test -n "$$CNT" || { echo "  FAIL  stub produced no result (no NOTIFY received?)"; cat /tmp/notify_sec.err; exit 1; }; \
	 test "$$TS" = "ok" || { echo "  FAIL  NOTIFY TSIG signature did not verify"; exit 1; }; \
	 test "$$CNT" -ge 2 || { echo "  FAIL  no retransmit (count=$$CNT) — sender did not retry the unacked NOTIFY"; exit 1; }; \
	 test "$$CNT" -le 4 || { echo "  FAIL  NOTIFY kept retransmitting (count=$$CNT) — ACK did not stop it"; exit 1; }; \
	 test "$$AK" = "yes" || { echo "  FAIL  stub never acked"; exit 1; }; \
	 echo "  OK  NOTIFY is TSIG-signed, retried while unacked, and stops on the secondary's ACK"

# PTR / reverse zones (CLAUDE-discovery.md Gap 4). Configures a reverse zone
# 0.0.10.in-addr.arpa and checks four things: (1) a statically-provisioned
# zone:<rev>:PTR:* answers a PTR query; (2) with config:ddns_auto_ptr=1 a forward
# A UPDATE auto-creates the matching reverse PTR lease; (3) both PTR records
# travel in an AXFR of the reverse zone (static via zone:, lease via ddns:);
# (4) deleting the forward A retracts the auto-PTR. Needs Valkey + dig + nsupdate.
check-ptr: $(BIN_DEBUG)
	@echo "  CHECK  PTR/reverse zones: serve + auto-PTR + AXFR + retract (Valkey + dig + nsupdate)"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 command -v nsupdate >/dev/null || { echo "  SKIP  no nsupdate on PATH"; exit 0; };\
	 FWD=example.local; REV=0.0.10.in-addr.arpa;                                       \
	 HOST=ptrhost.dyn.$$FWD; IP=10.0.0.42; REVNAME=42.0.0.10.in-addr.arpa;             \
	 STATREV=99.0.0.10.in-addr.arpa; STATTGT=static.$$FWD;                             \
	 REV6=8.b.d.0.1.0.0.2.ip6.arpa; HOST6=ptr6.dyn.$$FWD; IP6=2001:db8::5;             \
	 SAVE_TS=$$($$VC get config:tsig_secret_b64); SAVE_AP=$$($$VC get config:ddns_auto_ptr); \
	 SAVE_AX=$$($$VC get config:axfr_allow);                                           \
	 $$VC del config:tsig_secret_b64 >/dev/null;                                       \
	 $$VC set config:ddns_auto_ptr 1 >/dev/null;                                       \
	 $$VC set config:axfr_allow 127.0.0.1 >/dev/null;                                  \
	 $$VC set zone_table:$$REV "ns1.$$REV|hostmaster.$$REV|10|3600|900|604800|300|127.0.0.1|" >/dev/null; \
	 $$VC set zone_table:$$REV6 "ns1.$$REV6|hostmaster.$$REV6|10|3600|900|604800|300|127.0.0.1|" >/dev/null; \
	 $$VC set zone:$$REV:PTR:$$STATREV "120|$$STATTGT" >/dev/null;                     \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_ptr.log 2>&1 & DNS=$$!;     \
	 sleep 1.5;                                                                        \
	 STAT=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$STATREV PTR +time=2 +tries=1 | head -1); \
	 printf 'server 127.0.0.1 $(TPORT)\nzone %s\nupdate add %s 60 A %s\nsend\n' "$$FWD" "$$HOST" "$$IP" | nsupdate >/dev/null 2>&1; \
	 printf 'server 127.0.0.1 $(TPORT)\nzone %s\nupdate add %s 60 AAAA %s\nsend\n' "$$FWD" "$$HOST6" "$$IP6" | nsupdate >/dev/null 2>&1; \
	 sleep 0.3;                                                                        \
	 AUTO=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$REVNAME PTR +time=2 +tries=1 | head -1); \
	 AX=$$(dig +nocookie @127.0.0.1 -p $(TPORT) $$REV AXFR +time=3 +tries=1 | awk '$$4=="PTR"{print $$1" "$$5}'); \
	 AUTO6=$$(dig +nocookie @127.0.0.1 -p $(TPORT) $$REV6 AXFR +time=3 +tries=1 | awk '$$4=="PTR"{print $$5}' | head -1); \
	 printf 'server 127.0.0.1 $(TPORT)\nzone %s\nupdate delete %s A\nsend\n' "$$FWD" "$$HOST" | nsupdate >/dev/null 2>&1; \
	 sleep 0.3;                                                                        \
	 GONE=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$REVNAME PTR +time=2 +tries=1 | head -1); \
	 kill $$DNS 2>/dev/null || true;                                                   \
	 $$VC del zone_table:$$REV zone_table:$$REV6 zone:$$REV:PTR:$$STATREV ddns:$$REV:PTR:$$REVNAME ddns:$$FWD:A:$$HOST ddns:$$FWD:AAAA:$$HOST6 config:zone:$$REV:serial config:zone:$$REV6:serial >/dev/null; \
	 for k in $$($$VC --scan --pattern "dnssec:$$REV:*") $$($$VC --scan --pattern "dnssec:$$REV6:*") $$($$VC --scan --pattern "ddns:$$REV6:*") $$($$VC --scan --pattern "ixfr:$$REV:*") $$($$VC --scan --pattern "ixfr:$$REV6:*"); do $$VC del "$$k" >/dev/null; done; \
	 if [ -n "$$SAVE_TS" ]; then $$VC set config:tsig_secret_b64 "$$SAVE_TS" >/dev/null; fi; \
	 if [ -n "$$SAVE_AP" ]; then $$VC set config:ddns_auto_ptr "$$SAVE_AP" >/dev/null; else $$VC del config:ddns_auto_ptr >/dev/null; fi; \
	 if [ -n "$$SAVE_AX" ]; then $$VC set config:axfr_allow "$$SAVE_AX" >/dev/null; else $$VC del config:axfr_allow >/dev/null; fi; \
	 echo "  static=[$$STAT] auto=[$$AUTO] auto6=[$$AUTO6] gone=[$$GONE]"; echo "$$AX" | sed 's/^/    AXFR PTR /'; \
	 test "$$STAT" = "$$STATTGT." || { echo "  FAIL  static PTR not served (got [$$STAT])"; exit 1; }; \
	 test "$$AUTO" = "$$HOST." || { echo "  FAIL  auto-PTR not created on forward UPDATE (got [$$AUTO])"; exit 1; }; \
	 test "$$AUTO6" = "$$HOST6." || { echo "  FAIL  IPv6 auto-PTR wrong/missing (nibble order?) (got [$$AUTO6])"; exit 1; }; \
	 echo "$$AX" | grep -q "^$$STATREV. $$STATTGT.$$" || { echo "  FAIL  static PTR missing from AXFR"; exit 1; }; \
	 echo "$$AX" | grep -q "^$$REVNAME. $$HOST.$$" || { echo "  FAIL  auto-PTR lease missing from AXFR"; exit 1; }; \
	 test -z "$$GONE" || { echo "  FAIL  auto-PTR not retracted after forward delete (still [$$GONE])"; exit 1; }; \
	 echo "  OK  reverse zone served (static+auto, v4+v6), PTRs transfer in AXFR, retract on delete"

# mTLS on the DoT/transfer listener (hidden-master plan Gap 1). With
# config:dot_require_client_cert=1 + a CA, the DoT port must reject a TLS client
# that presents no client cert (TLS "certificate required" alert) and accept one
# that presents a CA-signed cert; with the flag off the port stays open for
# ordinary RFC 7858 clients. Uses openssl to mint a throwaway CA + server +
# client cert and openssl s_client to probe the handshake. Needs Valkey +
# openssl; restores the TLS config afterward.
check-dot-mtls: $(BIN_DEBUG)
	@echo "  CHECK  mTLS on the DoT/transfer listener (requires Valkey + openssl)"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 command -v openssl >/dev/null || { echo "  SKIP  no openssl on PATH"; exit 0; };  \
	 D=$$(mktemp -d);                                                                  \
	 EC="-newkey ec -pkeyopt ec_paramgen_curve:prime256v1 -nodes";                     \
	 openssl req -x509 $$EC -keyout $$D/ca.key -out $$D/ca.pem -days 2 -subj "/CN=test-ca" >/dev/null 2>&1; \
	 openssl req $$EC -keyout $$D/srv.key -out $$D/srv.csr -subj "/CN=dns.test" >/dev/null 2>&1; \
	 openssl x509 -req -in $$D/srv.csr -CA $$D/ca.pem -CAkey $$D/ca.key -CAcreateserial -out $$D/srv.pem -days 2 >/dev/null 2>&1; \
	 openssl req $$EC -keyout $$D/cli.key -out $$D/cli.csr -subj "/CN=secondary1" >/dev/null 2>&1; \
	 openssl x509 -req -in $$D/cli.csr -CA $$D/ca.pem -CAkey $$D/ca.key -CAcreateserial -out $$D/cli.pem -days 2 >/dev/null 2>&1; \
	 SAVE_C=$$($$VC get config:tls_cert_pem); SAVE_K=$$($$VC get config:tls_key_pem);  \
	 SAVE_A=$$($$VC get config:mtls_ca_pem); SAVE_R=$$($$VC get config:dot_require_client_cert); \
	 $$VC set config:tls_cert_pem "$$(cat $$D/srv.pem)" >/dev/null;                     \
	 $$VC set config:tls_key_pem "$$(cat $$D/srv.key)" >/dev/null;                      \
	 $$VC set config:mtls_ca_pem "$$(cat $$D/ca.pem)" >/dev/null;                       \
	 $$VC set config:dot_require_client_cert 1 >/dev/null;                             \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_dotm.log 2>&1 & DNS=$$!;    \
	 sleep 1.5;                                                                        \
	 NOCERT=$$(echo | openssl s_client -connect 127.0.0.1:8853 -CAfile $$D/ca.pem 2>&1 | grep -c "certificate required"); \
	 WITHCERT=$$(echo | openssl s_client -connect 127.0.0.1:8853 -cert $$D/cli.pem -key $$D/cli.key -CAfile $$D/ca.pem 2>&1 | grep -c "Verify return code: 0"); \
	 WC_ALERT=$$(echo | openssl s_client -connect 127.0.0.1:8853 -cert $$D/cli.pem -key $$D/cli.key -CAfile $$D/ca.pem 2>&1 | grep -c "certificate required"); \
	 kill $$DNS 2>/dev/null || true; sleep 0.3;                                        \
	 $$VC set config:dot_require_client_cert 0 >/dev/null;                             \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_dotm2.log 2>&1 & DNS=$$!;   \
	 sleep 1.5;                                                                        \
	 OPEN=$$(echo | openssl s_client -connect 127.0.0.1:8853 -CAfile $$D/ca.pem 2>&1 | grep -c "Verify return code: 0"); \
	 OPEN_ALERT=$$(echo | openssl s_client -connect 127.0.0.1:8853 -CAfile $$D/ca.pem 2>&1 | grep -c "certificate required"); \
	 kill $$DNS 2>/dev/null || true;                                                   \
	 if [ -n "$$SAVE_C" ]; then $$VC set config:tls_cert_pem "$$SAVE_C" >/dev/null; else $$VC del config:tls_cert_pem >/dev/null; fi; \
	 if [ -n "$$SAVE_K" ]; then $$VC set config:tls_key_pem "$$SAVE_K" >/dev/null; else $$VC del config:tls_key_pem >/dev/null; fi; \
	 if [ -n "$$SAVE_A" ]; then $$VC set config:mtls_ca_pem "$$SAVE_A" >/dev/null; else $$VC del config:mtls_ca_pem >/dev/null; fi; \
	 if [ -n "$$SAVE_R" ]; then $$VC set config:dot_require_client_cert "$$SAVE_R" >/dev/null; else $$VC del config:dot_require_client_cert >/dev/null; fi; \
	 rm -rf $$D;                                                                       \
	 echo "  mTLS on:  no-cert refused=$$NOCERT  with-cert ok=$$WITHCERT (alert=$$WC_ALERT)  | mTLS off: no-cert open=$$OPEN (alert=$$OPEN_ALERT)"; \
	 test "$$NOCERT" -ge 1   || { echo "  FAIL  mTLS on: no-cert client was NOT refused"; exit 1; }; \
	 test "$$WITHCERT" -ge 1 -a "$$WC_ALERT" -eq 0 || { echo "  FAIL  mTLS on: valid client cert was not accepted"; exit 1; }; \
	 test "$$OPEN" -ge 1 -a "$$OPEN_ALERT" -eq 0 || { echo "  FAIL  mTLS off: ordinary DoT client was refused (should stay open)"; exit 1; }; \
	 echo "  OK  mTLS refuses no-cert, accepts CA-signed cert, and stays open when disabled"

# AXFR completeness (CLAUDE-discovery.md Gap 1). A full transfer historically
# carried only the compile-time static_zone[] + DNSKEY + SOA; records
# provisioned at runtime (zone:<zone>:* from the mgmt API/DDNS, ddns:<zone>:*
# dynamic leases) were served locally but never transferred, leaving a secondary
# with a near-empty zone. Provision a multi-IP A, a TXT, and a ddns A lease,
# AXFR the zone, and assert all three appear (and the transfer completes — each
# message must echo the request ID, RFC 5936). Needs Valkey + dig + valkey-cli.
check-axfr: $(BIN_DEBUG)
	@echo "  CHECK  AXFR transfers runtime records (requires Valkey + dig)"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 Z=example.local;                                                                  \
	 SAVE_AX=$$($$VC get config:axfr_allow);                                           \
	 $$VC set config:axfr_allow 127.0.0.1 >/dev/null;                                  \
	 $$VC set zone:$$Z:A:web.$$Z "120|10.1.2.3|10.1.2.4" >/dev/null;                   \
	 $$VC set zone:$$Z:TXT:info.$$Z "120|hello-axfr" >/dev/null;                       \
	 $$VC set ddns:$$Z:A:dyn.$$Z 10.9.9.9 EX 300 >/dev/null;                           \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_axfr.log 2>&1 & DNS=$$!;    \
	 sleep 1.5;                                                                        \
	 OUT=$$(dig +noall +answer @127.0.0.1 -p $(TPORT) $$Z AXFR +time=5 +tries=1);          \
	 kill $$DNS 2>/dev/null || true;                                                   \
	 $$VC del zone:$$Z:A:web.$$Z zone:$$Z:TXT:info.$$Z ddns:$$Z:A:dyn.$$Z >/dev/null;  \
	 if [ -n "$$SAVE_AX" ]; then $$VC set config:axfr_allow "$$SAVE_AX" >/dev/null; else $$VC del config:axfr_allow >/dev/null; fi; \
	 A1=$$(echo "$$OUT" | grep -c "^web\.$$Z\..*A.10\.1\.2\.3");                        \
	 A2=$$(echo "$$OUT" | grep -c "^web\.$$Z\..*A.10\.1\.2\.4");                        \
	 TX=$$(echo "$$OUT" | grep -c "^info\.$$Z\..*TXT.*hello-axfr");                     \
	 DY=$$(echo "$$OUT" | grep -c "^dyn\.$$Z\..*A.10\.9\.9\.9");                        \
	 SO=$$(echo "$$OUT" | grep -c "[[:space:]]SOA[[:space:]]");                         \
	 echo "  transferred: web/.3=$$A1 web/.4=$$A2 info-TXT=$$TX ddns-dyn=$$DY soa_count=$$SO"; \
	 test "$$A1" -ge 1 -a "$$A2" -ge 1 || { echo "  FAIL  multi-IP zone:A not fully transferred"; exit 1; }; \
	 test "$$TX" -ge 1 || { echo "  FAIL  provisioned zone:TXT not transferred"; exit 1; }; \
	 test "$$DY" -ge 1 || { echo "  FAIL  ddns:* dynamic lease not transferred"; exit 1; }; \
	 test "$$SO" -ge 2 || { echo "  FAIL  transfer did not complete (need opening+closing SOA; ID echo?)"; exit 1; }; \
	 echo "  OK  runtime zone:* and ddns:* records present; transfer bracketed by SOA"

# RFC 1995 IXFR — *server-side* incremental transfer. Seed a throwaway zone at a
# known serial plus a journal (ixfr:<zone>:journal) of A adds/deletes chaining
# the client's serial up to current, then drive a small IXFR client
# (tests/ixfr_client.py) and assert: (1) an in-range serial yields a correct
# incremental diff with the right add/delete sections, (2) a serial not in the
# journal falls back to AXFR, (3) the current serial replies "up to date".
# Needs Valkey + python3.
check-ixfr: $(BIN_DEBUG)
	@echo "  CHECK  RFC 1995 server IXFR: diff framing + AXFR fallback (Valkey + python3)"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 command -v python3 >/dev/null || { echo "  SKIP  no python3 on PATH"; exit 0; };  \
	 Z=ixfr.test; CUR=103;                                                             \
	 SAVE_AX=$$($$VC get config:axfr_allow);                                           \
	 $$VC set config:axfr_allow 127.0.0.1 >/dev/null;                                  \
	 $$VC set zone_table:$$Z "ns1.$$Z|hostmaster.$$Z|$$CUR|3600|900|604800|300|127.0.0.1|" >/dev/null; \
	 $$VC set config:zone:$$Z:serial $$CUR >/dev/null;                                 \
	 $$VC set zone:$$Z:A:www.$$Z "120|10.9.9.9" >/dev/null;                            \
	 $$VC del ixfr:$$Z:journal >/dev/null;                                             \
	 $$VC rpush ixfr:$$Z:journal "100|101|A|host1.$$Z|10.0.0.1" >/dev/null;            \
	 $$VC rpush ixfr:$$Z:journal "101|102|A|host2.$$Z|10.0.0.2" >/dev/null;            \
	 $$VC rpush ixfr:$$Z:journal "102|103|D|host1.$$Z|10.0.0.1" >/dev/null;            \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_ixfr.log 2>&1 & DNS=$$!;    \
	 sleep 1.5;                                                                        \
	 INC=$$(python3 tests/ixfr_client.py 127.0.0.1 $(TPORT) $$Z 100 2>/dev/null);          \
	 FB=$$(python3 tests/ixfr_client.py 127.0.0.1 $(TPORT) $$Z 50 2>/dev/null);            \
	 UP=$$(python3 tests/ixfr_client.py 127.0.0.1 $(TPORT) $$Z 103 2>/dev/null);           \
	 kill $$DNS 2>/dev/null || true;                                                   \
	 $$VC del zone_table:$$Z config:zone:$$Z:serial zone:$$Z:A:www.$$Z ixfr:$$Z:journal >/dev/null; \
	 for k in $$($$VC --scan --pattern "dnssec:$$Z:*") $$($$VC --scan --pattern "zone:$$Z:*"); do $$VC del "$$k" >/dev/null; done; \
	 if [ -n "$$SAVE_AX" ]; then $$VC set config:axfr_allow "$$SAVE_AX" >/dev/null; else $$VC del config:axfr_allow >/dev/null; fi; \
	 echo "  --- incremental (serial 100) ---"; echo "$$INC" | sed 's/^/    /';        \
	 echo "  --- fallback (serial 50): $$(echo "$$FB" | grep '^MODE') | uptodate (103): $$(echo "$$UP" | grep '^MODE')"; \
	 echo "$$INC" | grep -q "^MODE incremental" || { echo "  FAIL  in-range serial did not yield an incremental transfer"; exit 1; }; \
	 echo "$$INC" | grep -q "^ADD host1.$$Z A 10.0.0.1" || { echo "  FAIL  missing ADD host1 10.0.0.1"; exit 1; }; \
	 echo "$$INC" | grep -q "^ADD host2.$$Z A 10.0.0.2" || { echo "  FAIL  missing ADD host2 10.0.0.2"; exit 1; }; \
	 echo "$$INC" | grep -q "^DEL host1.$$Z A 10.0.0.1" || { echo "  FAIL  missing DEL host1 10.0.0.1 (op field ignored?)"; exit 1; }; \
	 echo "$$INC" | grep -q "^END 103" || { echo "  FAIL  incremental did not close at current serial 103"; exit 1; }; \
	 echo "$$FB"  | grep -q "^MODE axfr" || { echo "  FAIL  out-of-journal serial did not fall back to AXFR"; exit 1; }; \
	 echo "$$UP"  | grep -q "^MODE uptodate" || { echo "  FAIL  current-serial request was not answered up-to-date"; exit 1; }; \
	 echo "  OK  incremental diff correct (adds+delete), AXFR fallback + up-to-date handled"

# RFC 1995 IXFR — *client-side* incremental apply. Run dnsd as a secondary
# pointed at an IXFR-capable stub master (tests/ixfr_master.py): the first pull
# is a full AXFR (serial 0 → 100, records keep+old), then a NOTIFY drives a
# re-pull which now carries the secondary's serial as an IXFR request; the stub
# answers with a diff (delete old, add new, serial → 101). Assert the secondary
# applied the diff incrementally: keep untouched, old removed, new present,
# serial bumped. Needs Valkey + dig + python3; restores config afterward.
check-ixfr-client: $(BIN_DEBUG)
	@echo "  CHECK  secondary IXFR incremental apply (Valkey + dig + python3)"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 command -v python3 >/dev/null || { echo "  SKIP  no python3 on PATH"; exit 0; };  \
	 Z=ixfrpull.test; P=5392;                                                          \
	 SAVE_ROLE=$$($$VC get config:zone_role); SAVE_PH=$$($$VC get config:primary_host);\
	 SAVE_PP=$$($$VC get config:primary_port); SAVE_PT=$$($$VC get config:primary_tls);\
	 python3 tests/ixfr_master.py 127.0.0.1 $$P $$Z >/tmp/ixfr_master.log 2>&1 & M=$$!;\
	 $$VC set zone_table:$$Z "ns1.$$Z|hostmaster.$$Z|1|3600|900|604800|300|127.0.0.1|" >/dev/null; \
	 for k in $$($$VC --scan --pattern "zone:$$Z:*"); do $$VC del "$$k" >/dev/null; done; \
	 $$VC del config:zone:$$Z:serial >/dev/null;                                       \
	 $$VC set config:zone_role secondary >/dev/null;                                   \
	 $$VC set config:primary_host 127.0.0.1 >/dev/null;                                \
	 $$VC set config:primary_port $$P >/dev/null;                                      \
	 $$VC set config:primary_tls 0 >/dev/null;                                         \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_ixc.log 2>&1 & DNS=$$!;     \
	 sleep 4;                                                                          \
	 S1=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$Z SOA +time=2 +tries=1 | awk '{print $$3}'); \
	 K1=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) keep.$$Z A +time=2 +tries=1);       \
	 O1=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) old.$$Z A +time=2 +tries=1);        \
	 dig +opcode=notify +nocookie @127.0.0.1 -p $(TPORT) $$Z SOA +time=2 +tries=1 >/dev/null 2>&1; \
	 sleep 1.5;                                                                        \
	 S2=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$Z SOA +time=2 +tries=1 | awk '{print $$3}'); \
	 K2=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) keep.$$Z A +time=2 +tries=1);       \
	 O2=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) old.$$Z A +time=2 +tries=1);        \
	 N2=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) new.$$Z A +time=2 +tries=1);        \
	 kill $$DNS $$M 2>/dev/null || true;                                               \
	 $$VC del zone_table:$$Z config:primary_host config:primary_port config:primary_tls config:zone:$$Z:serial >/dev/null; \
	 for k in $$($$VC --scan --pattern "zone:$$Z:*") $$($$VC --scan --pattern "dnssec:$$Z:*") $$($$VC --scan --pattern "ixfr:$$Z:*"); do $$VC del "$$k" >/dev/null; done; \
	 if [ -n "$$SAVE_ROLE" ]; then $$VC set config:zone_role "$$SAVE_ROLE" >/dev/null; else $$VC del config:zone_role >/dev/null; fi; \
	 if [ -n "$$SAVE_PH" ]; then $$VC set config:primary_host "$$SAVE_PH" >/dev/null; fi; \
	 if [ -n "$$SAVE_PP" ]; then $$VC set config:primary_port "$$SAVE_PP" >/dev/null; fi; \
	 if [ -n "$$SAVE_PT" ]; then $$VC set config:primary_tls "$$SAVE_PT" >/dev/null; fi; \
	 echo "  startup(AXFR): serial=$$S1 keep=[$$K1] old=[$$O1] | after NOTIFY(IXFR): serial=$$S2 keep=[$$K2] old=[$$O2] new=[$$N2]"; \
	 test "$$S1" = "100" || { echo "  FAIL  initial AXFR serial ($$S1 != 100)"; exit 1; }; \
	 test "$$O1" = "10.0.0.2" || { echo "  FAIL  initial AXFR did not load old.$$Z"; exit 1; }; \
	 test "$$S2" = "101" || { echo "  FAIL  IXFR did not advance serial ($$S2 != 101)"; exit 1; }; \
	 test "$$K2" = "10.0.0.1" || { echo "  FAIL  IXFR clobbered an untouched record (keep.$$Z)"; exit 1; }; \
	 test -z "$$O2" || { echo "  FAIL  IXFR delete not applied (old.$$Z still [$$O2])"; exit 1; }; \
	 test "$$N2" = "10.0.3.3" || { echo "  FAIL  IXFR add not applied (new.$$Z=[$$N2])"; exit 1; }; \
	 echo "  OK  secondary applied the IXFR diff (add+delete) without a full re-transfer"

# RFC 7344 regression: the CDS RRset must equal the DS the zone publishes, and
# CDNSKEY must equal the zone's KSK DNSKEY(s). Guards against CDS/CDNSKEY drifting
# back to the ZSK or to the wrong rdata format. Needs Valkey + dig.
check-cds: $(BIN_DEBUG)
	@echo "  CHECK  RFC 7344 CDS==DS and CDNSKEY==KSK (requires Valkey + dig)"
	@LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_cds.log 2>&1 &                                          \
	 DNS_PID=$$!;                                                                       \
	 sleep 1;                                                                           \
	 Z=example.local;                                                                   \
	 dig @127.0.0.1 -p $(TPORT) $$Z DS      +short | sort > /tmp/cds_ds.txt;                \
	 dig @127.0.0.1 -p $(TPORT) $$Z CDS     +short | sort > /tmp/cds_cds.txt;               \
	 dig @127.0.0.1 -p $(TPORT) $$Z CDNSKEY +short | sort > /tmp/cds_cdk.txt;               \
	 dig @127.0.0.1 -p $(TPORT) $$Z DNSKEY  +short | grep '^257' | sort > /tmp/cds_ksk.txt; \
	 kill $$DNS_PID 2>/dev/null || true;                                                \
	 test -s /tmp/cds_ds.txt || { echo "  FAIL  no DS/CDS emitted (zone unsigned?)"; exit 1; }; \
	 diff /tmp/cds_ds.txt /tmp/cds_cds.txt || { echo "  FAIL  CDS != DS"; exit 1; };    \
	 diff /tmp/cds_cdk.txt /tmp/cds_ksk.txt || { echo "  FAIL  CDNSKEY != KSK DNSKEY"; exit 1; }; \
	 echo "  OK  CDS==DS and CDNSKEY==KSK"

# RFC 9432 catalog zones: a member listed only in a catalog (a version-"2" zone
# with a <id>.zones.<cat> PTR) must be auto-provisioned (served + DNSSEC-signed)
# and then deprovisioned when the PTR is removed. dnsd never writes zone_table:*
# for the member — provisioning is in-memory, re-derived from the catalog. Needs
# Valkey + dig + valkey-cli/redis-cli; uses throwaway names and cleans up after.
check-catalog: $(BIN_DEBUG)
	@echo "  CHECK  RFC 9432 catalog provision/deprovision (requires Valkey + dig)"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 CZ=catalog.test; MZ=member.test;                                                  \
	 $$VC set zone_table:$$CZ "ns1.$$CZ|hostmaster.$$CZ|3|3600|900|604800|300|127.0.0.1|" >/dev/null; \
	 $$VC set zone:$$CZ:TXT:version.$$CZ "300|2" >/dev/null;                           \
	 $$VC set zone:$$CZ:PTR:m1.zones.$$CZ "300|$$MZ" >/dev/null;                       \
	 $$VC set zone:$$MZ:A:www.$$MZ "300|10.9.8.7" >/dev/null;                          \
	 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_cat.log 2>&1 &                                         \
	 DNS_PID=$$!;                                                                      \
	 sleep 1.5;                                                                        \
	 A=$$(dig @127.0.0.1 -p $(TPORT) www.$$MZ A   +short +time=2 +tries=1);                \
	 S=$$(dig @127.0.0.1 -p $(TPORT) $$MZ     SOA +short +time=2 +tries=1);                \
	 D=$$(dig @127.0.0.1 -p $(TPORT) $$MZ     DS  +short +time=2 +tries=1);                \
	 $$VC del zone:$$CZ:PTR:m1.zones.$$CZ >/dev/null;                                  \
	 $$VC set config:catalog_test_poke 1 >/dev/null;                                   \
	 sleep 1.5;                                                                        \
	 A2=$$(dig @127.0.0.1 -p $(TPORT) www.$$MZ A +short +time=2 +tries=1);                 \
	 kill $$DNS_PID 2>/dev/null || true;                                               \
	 $$VC del zone_table:$$CZ zone:$$CZ:TXT:version.$$CZ zone:$$MZ:A:www.$$MZ config:catalog_test_poke >/dev/null 2>&1; \
	 for k in $$($$VC --scan --pattern "dnssec:$$CZ:*") $$($$VC --scan --pattern "dnssec:$$MZ:*") $$($$VC --scan --pattern "config:zone:$$MZ:*"); do $$VC del "$$k" >/dev/null 2>&1; done; \
	 echo "  provisioned: A=[$$A] SOA=[$$S] DS=[$$D]";                                 \
	 test "$$A" = "10.9.8.7" || { echo "  FAIL  member A not served after provisioning"; exit 1; }; \
	 test -n "$$S" || { echo "  FAIL  member SOA not served after provisioning"; exit 1; }; \
	 test -n "$$D" || { echo "  FAIL  member zone not DNSSEC-signed (no DS)"; exit 1; }; \
	 test -z "$$A2" || { echo "  FAIL  member still served after PTR removed ($$A2)"; exit 1; }; \
	 echo "  OK  member provisioned+signed, then deprovisioned on PTR removal"

# Out-of-zone forwarding (CLAUDE-forwarder.md). Bring up three stub upstreams
# (tests/fwd_upstream.py: a normal responder, a truncate-only responder, and a
# spoofing responder) and a dnsd configured to forward out-of-zone queries to
# them for localhost clients, then assert, restarting dnsd per phase so each
# reads fresh config:
#   1. forward + RA, *through* a dead first forwarder (failover to the 2nd);
#   2. +norecurse out-of-zone is REFUSED (RD gating);
#   3. an in-zone name is still answered authoritatively (AA, never forwarded);
#   4. fail-closed — a non-matching forward_allow REFUSEs the same query;
#   5. TC over UDP makes a TCP client's query complete over TCP upstream;
#   6. a forged upstream transaction ID is rejected (RFC 5452) -> SERVFAIL.
# Needs Valkey + dig + valkey-cli + python3; uses throwaway config keys and
# restores the forwarding config afterward.
check-forwarder: $(BIN_DEBUG)
	@echo "  CHECK  out-of-zone forwarding + failover + TC->TCP + RFC 5452 anti-spoof"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 command -v python3 >/dev/null || { echo "  SKIP  no python3 on PATH"; exit 0; };  \
	 ANS=203.0.113.45; QN=forwarded.example.net;                                       \
	 NORM=5399; TRUNC=5397; SPOOF=5396; DEAD=5398;                                     \
	 SAVE_EN=$$($$VC get config:forward_enabled);                                      \
	 SAVE_FW=$$($$VC get config:forwarders);                                           \
	 SAVE_AL=$$($$VC get config:forward_allow);                                        \
	 SAVE_TO=$$($$VC get config:forward_timeout_ms);                                   \
	 python3 tests/fwd_upstream.py 127.0.0.1 $$NORM  $$ANS normal   >/tmp/fwd_norm.log  2>&1 & P1=$$!; \
	 python3 tests/fwd_upstream.py 127.0.0.1 $$TRUNC $$ANS truncate >/tmp/fwd_trunc.log 2>&1 & P2=$$!; \
	 python3 tests/fwd_upstream.py 127.0.0.1 $$SPOOF $$ANS spoof    >/tmp/fwd_spoof.log 2>&1 & P3=$$!; \
	 $$VC set config:forward_enabled 1 >/dev/null;                                     \
	 $$VC set config:forward_timeout_ms 600 >/dev/null;                                \
	 sleep 0.3;                                                                        \
	 $$VC set config:forward_allow 127.0.0.0/8 >/dev/null;                             \
	 $$VC set config:forwarders 127.0.0.1:$$DEAD,127.0.0.1:$$NORM >/dev/null;          \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_fwd1.log 2>&1 & DNS=$$!;    \
	 sleep 1.5;                                                                        \
	 FWD=$$(dig +nocookie @127.0.0.1 -p $(TPORT) $$QN A +time=3 +tries=1);                 \
	 FWD_A=$$(echo "$$FWD" | awk '/^'$$QN'\./ && $$4=="A"{print $$5; exit}');          \
	 FWD_RA=$$(echo "$$FWD" | grep -Ec 'flags:.* ra');                                 \
	 NR=$$(dig @127.0.0.1 -p $(TPORT) $$QN A +norecurse +time=2 +tries=1 | grep -c 'status: REFUSED'); \
	 IN=$$(dig @127.0.0.1 -p $(TPORT) example.local SOA +time=2 +tries=1 | grep -Ec 'flags:.* aa'); \
	 kill $$DNS 2>/dev/null || true; sleep 0.3;                                        \
	 $$VC set config:forward_allow 192.0.2.0/24 >/dev/null;                            \
	 $$VC set config:forwarders 127.0.0.1:$$NORM >/dev/null;                           \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_fwd2.log 2>&1 & DNS=$$!;    \
	 sleep 1.5;                                                                        \
	 CLOSED=$$(dig @127.0.0.1 -p $(TPORT) $$QN A +time=2 +tries=1 | grep -c 'status: REFUSED'); \
	 kill $$DNS 2>/dev/null || true; sleep 0.3;                                        \
	 $$VC set config:forward_allow 127.0.0.0/8 >/dev/null;                             \
	 $$VC set config:forwarders 127.0.0.1:$$TRUNC >/dev/null;                          \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_fwd3.log 2>&1 & DNS=$$!;    \
	 sleep 1.5;                                                                        \
	 TCPA=$$(dig +tcp +nocookie @127.0.0.1 -p $(TPORT) $$QN A +time=3 +tries=1 | awk '/^'$$QN'\./ && $$4=="A"{print $$5; exit}'); \
	 kill $$DNS 2>/dev/null || true; sleep 0.3;                                        \
	 $$VC set config:forwarders 127.0.0.1:$$SPOOF >/dev/null;                          \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_fwd4.log 2>&1 & DNS=$$!;    \
	 sleep 1.5;                                                                        \
	 SPOOFED=$$(dig +nocookie @127.0.0.1 -p $(TPORT) $$QN A +time=3 +tries=1 | grep -c 'status: SERVFAIL'); \
	 kill $$DNS $$P1 $$P2 $$P3 2>/dev/null || true;                                    \
	 if [ -n "$$SAVE_EN" ]; then $$VC set config:forward_enabled "$$SAVE_EN" >/dev/null; else $$VC del config:forward_enabled >/dev/null; fi; \
	 if [ -n "$$SAVE_FW" ]; then $$VC set config:forwarders "$$SAVE_FW" >/dev/null; else $$VC del config:forwarders >/dev/null; fi; \
	 if [ -n "$$SAVE_AL" ]; then $$VC set config:forward_allow "$$SAVE_AL" >/dev/null; else $$VC del config:forward_allow >/dev/null; fi; \
	 if [ -n "$$SAVE_TO" ]; then $$VC set config:forward_timeout_ms "$$SAVE_TO" >/dev/null; else $$VC del config:forward_timeout_ms >/dev/null; fi; \
	 echo "  forward+failover: A=[$$FWD_A] ra=$$FWD_RA  norecurse_refused=$$NR  in_zone_aa=$$IN"; \
	 echo "  fail-closed_refused=$$CLOSED  tc->tcp A=[$$TCPA]  spoofed_id_servfail=$$SPOOFED"; \
	 test "$$FWD_A" = "$$ANS" || { echo "  FAIL  out-of-zone not forwarded / failover broken (expected $$ANS)"; exit 1; }; \
	 test "$$FWD_RA" -ge 1   || { echo "  FAIL  forwarded reply missing RA flag"; exit 1; }; \
	 test "$$NR" -ge 1       || { echo "  FAIL  +norecurse out-of-zone not REFUSED"; exit 1; }; \
	 test "$$IN" -ge 1       || { echo "  FAIL  in-zone query no longer authoritative (AA)"; exit 1; }; \
	 test "$$CLOSED" -ge 1   || { echo "  FAIL  fail-closed: out-of-ACL client was not REFUSED"; exit 1; }; \
	 test "$$TCPA" = "$$ANS"  || { echo "  FAIL  TC->TCP: TCP client did not get the full forwarded answer"; exit 1; }; \
	 test "$$SPOOFED" -ge 1  || { echo "  FAIL  RFC 5452: forged upstream ID was not rejected (expected SERVFAIL)"; exit 1; }; \
	 echo "  OK  forward+RA, failover, RD-gating, in-zone AA, fail-closed, TC->TCP, anti-spoof"

# A/AAAA load-balancing rotation (CLAUDE-loadbalance.md Gap 1). Provision a
# 3-address A RRset, then assert: with config:lb_mode=rr the emission order
# rotates across queries (>=2 distinct first-addresses) while all 3 addresses
# are always present and DNSSEC RRSIGs are still emitted (per-RR signing is
# rotation-neutral); with lb_mode=none the order is stable. Needs Valkey + dig
# + valkey-cli; uses a throwaway name and restores config:lb_mode afterward.
check-lb: $(BIN_DEBUG)
	@echo "  CHECK  A/AAAA load-balancing rotation (requires Valkey + dig)"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 QN=lb.example.local; REC=zone:example.local:A:$$QN;                               \
	 SAVE_LB=$$($$VC get config:lb_mode);                                              \
	 $$VC set $$REC "30|10.0.0.1|10.0.0.2|10.0.0.3" >/dev/null;                        \
	 $$VC set config:lb_mode rr >/dev/null;                                            \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_lb1.log 2>&1 & DNS=$$!;     \
	 sleep 1.5;                                                                        \
	 FIRSTS=""; NLINES_MIN=9;                                                          \
	 for i in 1 2 3 4 5 6; do                                                          \
	   OUT=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$QN A +time=2 +tries=1);        \
	   F=$$(echo "$$OUT" | head -1);                                                   \
	   C=$$(echo "$$OUT" | grep -c '^10\.0\.0\.');                                     \
	   FIRSTS="$$FIRSTS $$F";                                                          \
	   if [ "$$C" -lt 3 ]; then NLINES_MIN=0; fi;                                      \
	 done;                                                                             \
	 DISTINCT=$$(echo $$FIRSTS | tr ' ' '\n' | sort -u | grep -c '^10\.0\.0\.');       \
	 SIGS=$$(dig +dnssec +nocookie @127.0.0.1 -p $(TPORT) $$QN A +time=2 +tries=1 | grep -c 'RRSIG'); \
	 kill $$DNS 2>/dev/null || true; sleep 0.3;                                        \
	 $$VC set config:lb_mode none >/dev/null;                                          \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_lb2.log 2>&1 & DNS=$$!;     \
	 sleep 1.5;                                                                        \
	 N1=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$QN A +time=2 +tries=1 | head -1); \
	 N2=$$(dig +short +nocookie @127.0.0.1 -p $(TPORT) $$QN A +time=2 +tries=1 | head -1); \
	 kill $$DNS 2>/dev/null || true;                                                   \
	 $$VC del $$REC >/dev/null;                                                        \
	 if [ -n "$$SAVE_LB" ]; then $$VC set config:lb_mode "$$SAVE_LB" >/dev/null; else $$VC del config:lb_mode >/dev/null; fi; \
	 echo "  rr: first-addr sequence =$$FIRSTS  (distinct=$$DISTINCT, all3each=$$NLINES_MIN, rrsigs=$$SIGS)"; \
	 echo "  none: first-addr q1=$$N1 q2=$$N2";                                        \
	 test "$$DISTINCT" -ge 2     || { echo "  FAIL  rr mode did not rotate the RRset (distinct first-addr < 2)"; exit 1; }; \
	 test "$$NLINES_MIN" -ge 3   || { echo "  FAIL  rotation dropped addresses (a response had <3 A records)"; exit 1; }; \
	 test "$$SIGS" -ge 1         || { echo "  FAIL  +dnssec returned no RRSIG for the rotated RRset"; exit 1; }; \
	 test -n "$$N1" -a "$$N1" = "$$N2" || { echo "  FAIL  lb_mode=none not stable ($$N1 vs $$N2)"; exit 1; }; \
	 echo "  OK  rr rotates (all addrs kept, RRSIGs intact), none is stable"

# A/AAAA load-balancing health checks (CLAUDE-loadbalance.md Gap 2). Provision a
# name with two addresses: 127.0.0.1 (a python TCP listener answers → healthy)
# and 127.0.0.2 (nothing listening → connection refused → down). With
# config:lb_health_enabled the query must serve only the healthy 127.0.0.1; after
# the listener is stopped (both down) it must fail open and serve both again.
# Runs dnsd on config:dns_port 5356 to avoid colliding with a desktop mDNS
# responder (avahi) on 5353. Needs Valkey + dig + python3.
check-lb-health: $(BIN_DEBUG)
	@echo "  CHECK  LB health checks: drop down addr, fail open when all down (Valkey + dig + python3)"
	@VC=$$(command -v valkey-cli || command -v redis-cli);                             \
	 test -n "$$VC" || { echo "  SKIP  no valkey-cli/redis-cli on PATH"; exit 0; };    \
	 command -v python3 >/dev/null || { echo "  SKIP  no python3 on PATH"; exit 0; };  \
	 Z=example.local; NAME=lbh.$$Z; HP=5394; DP=5356; REC=zone:$$Z:A:$$NAME;           \
	 SAVE_HE=$$($$VC get config:lb_health_enabled); SAVE_HT=$$($$VC get config:lb_health_targets); \
	 SAVE_HI=$$($$VC get config:lb_health_interval); SAVE_DP=$$($$VC get config:dns_port); \
	 $$VC set $$REC "30|127.0.0.1|127.0.0.2" >/dev/null;                               \
	 $$VC set config:lb_health_enabled 1 >/dev/null;                                   \
	 $$VC set config:lb_health_targets "$$NAME:$$HP" >/dev/null;                       \
	 $$VC set config:lb_health_interval 1 >/dev/null;                                  \
	 $$VC set config:dns_port $$DP >/dev/null;                                         \
	 python3 -c "import socket,time; s=socket.socket(); s.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1); s.bind(('127.0.0.1',$$HP)); s.listen(16); time.sleep(60)" >/dev/null 2>&1 & LIS=$$!; \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_lbh.log 2>&1 & DNS=$$!;     \
	 sleep 3;                                                                          \
	 UP=$$(dig +short +nocookie @127.0.0.1 -p $$DP $$NAME A +time=2 +tries=1 | sort | tr '\n' ' '); \
	 kill $$LIS 2>/dev/null || true;                                                   \
	 sleep 2.5;                                                                        \
	 BOTH=$$(dig +short +nocookie @127.0.0.1 -p $$DP $$NAME A +time=2 +tries=1 | sort | tr '\n' ' '); \
	 kill $$DNS 2>/dev/null || true;                                                   \
	 $$VC del $$REC config:lb_health_targets config:lb_health_interval >/dev/null;     \
	 if [ -n "$$SAVE_HE" ]; then $$VC set config:lb_health_enabled "$$SAVE_HE" >/dev/null; else $$VC del config:lb_health_enabled >/dev/null; fi; \
	 if [ -n "$$SAVE_HT" ]; then $$VC set config:lb_health_targets "$$SAVE_HT" >/dev/null; fi; \
	 if [ -n "$$SAVE_HI" ]; then $$VC set config:lb_health_interval "$$SAVE_HI" >/dev/null; fi; \
	 if [ -n "$$SAVE_DP" ]; then $$VC set config:dns_port "$$SAVE_DP" >/dev/null; else $$VC del config:dns_port >/dev/null; fi; \
	 echo "  healthy-only=[$$UP]  all-down(fail-open)=[$$BOTH]";                       \
	 echo "$$UP"   | grep -q "127.0.0.1" || { echo "  FAIL  healthy address 127.0.0.1 was not served"; exit 1; }; \
	 echo "$$UP"   | grep -q "127.0.0.2" && { echo "  FAIL  down address 127.0.0.2 was not filtered out"; exit 1; }; \
	 echo "$$BOTH" | grep -q "127.0.0.1" && echo "$$BOTH" | grep -q "127.0.0.2" || { echo "  FAIL  fail-open did not serve all addresses when every target was down"; exit 1; }; \
	 echo "  OK  unhealthy address dropped; fail-open serves all when every backend is down"

# resolverd smoke: bring up dnsd (authoritative upstream) and resolverd (caching
# proxy on LISTEN_PORT 5354), resolve example.local through the proxy and confirm
# it returns dnsd's answer. Needs Valkey + dig.
#
# dnsd runs on $(TPORT) (avahi-immune, like the rest of the suite) and resolverd
# forwards to it explicitly. --no-mdns keeps the .local query on the unicast
# upstream path instead of resolverd's mDNS multicast (port 5353), which is what
# used to pin this test to 5353 and let a stray avahi answer it.
check-resolverd: $(BIN_DEBUG) resolverd_debug
	@echo "  CHECK  resolverd caching proxy → dnsd (requires Valkey + dig)"
	@ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=$(TPORT) ./$(BIN_DEBUG) > /tmp/dnsd_rd.log 2>&1 & \
	 DNS_PID=$$!;                                                                       \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=5354                                       \
	     ./resolverd_debug --upstream 127.0.0.1:$(TPORT) --no-mdns                      \
	     > /tmp/resolverd_rd.log 2>&1 &                                                 \
	 RD_PID=$$!;                                                                        \
	 sleep 2;                                                                           \
	 A=$$(dig @127.0.0.1 -p 5354 example.local A +short +time=2 +tries=1);             \
	 kill $$DNS_PID $$RD_PID 2>/dev/null || true;                                       \
	 echo "  resolved via resolverd (:5354 → dnsd :$(TPORT)): A=[$$A]";                \
	 test "$$A" = "192.168.1.10" || { echo "  FAIL  resolverd did not return dnsd's answer"; exit 1; }; \
	 echo "  OK  resolverd proxied dnsd's answer"

# Regression: the Valkey persistent-cache load path. Seeds a positive entry and
# queries it with an unreachable upstream, so the answer can only come from
# cache_load_valkey(). Guards the bug where entry_remaining_ttl() ran before
# e->rrs was allocated (nrr>0, rrs==NULL) and crashed (SEGV @ 0x8) on the first
# Valkey cache hit after an in-memory miss (e.g. a freshly restarted resolverd).
check-resolverd-cache: resolverd_debug
	@echo "  CHECK  resolverd Valkey cache-load path (regression: NULL e->rrs)"
	@command -v valkey-cli >/dev/null 2>&1 || { echo "  SKIP  valkey-cli not found"; exit 0; }; \
	 KEY=dnscache:cacheregress.test:A; NOW=$$(date +%s);                               \
	 valkey-cli del $$KEY >/dev/null 2>&1 || true;                                     \
	 valkey-cli set $$KEY "1|0|0|0|$$NOW|1:300:4:5db8d822|" >/dev/null;                \
	 valkey-cli expire $$KEY 300 >/dev/null;                                           \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=5358                                      \
	     ./resolverd_debug --upstream 127.0.0.1:1 > /tmp/resolverd_cache.log 2>&1 &    \
	 RD_PID=$$!;                                                                       \
	 sleep 2;                                                                          \
	 A=$$(dig @127.0.0.1 -p 5358 cacheregress.test A +short +time=2 +tries=1);         \
	 ALIVE=0; kill -0 $$RD_PID 2>/dev/null && ALIVE=1;                                 \
	 kill $$RD_PID 2>/dev/null || true;                                               \
	 valkey-cli del $$KEY >/dev/null 2>&1 || true;                                     \
	 echo "  cache-hit A=[$$A] daemon_alive=$$ALIVE";                                  \
	 test "$$ALIVE" = 1 || { echo "  FAIL  resolverd crashed serving a Valkey cache hit"; cat /tmp/resolverd_cache.log; exit 1; }; \
	 test "$$A" = "93.184.216.34" || { echo "  FAIL  cache-load path returned wrong/empty answer"; exit 1; }; \
	 echo "  OK  served cached A from Valkey without crashing"

# RFC 7873 client-side DNS Cookies. A stub upstream refuses to answer until the
# client proves it holds a valid Server Cookie (first query → BADCOOKIE carrying
# a fresh Server Cookie; resolverd must learn it and retry). Asserts the upstream
# both sent a BADCOOKIE and later answered a cookie-validated query, and that the
# cookie-gated answer reached the client.
check-resolverd-cookie: resolverd_debug
	@echo "  CHECK  resolverd RFC 7873 DNS cookie exchange (BADCOOKIE retry)"
	@command -v python3 >/dev/null 2>&1 || { echo "  SKIP  python3 not found"; exit 0; }; \
	 python3 tests/cookie_upstream.py 127.0.0.1 5409 203.0.113.77 > /tmp/cookie_stub.log 2>&1 & \
	 STUB_PID=$$!;                                                                     \
	 ASAN_OPTIONS=detect_leaks=0 LISTEN_PORT=5360                                      \
	     ./resolverd_debug --upstream 127.0.0.1:5409 --no-dnssec --no-valkey          \
	     > /tmp/resolverd_cookie.log 2>&1 &                                            \
	 RD_PID=$$!;                                                                       \
	 sleep 2;                                                                          \
	 A=$$(dig @127.0.0.1 -p 5360 cookie.test A +short +time=3 +tries=1);              \
	 kill $$RD_PID $$STUB_PID 2>/dev/null || true;                                     \
	 echo "  resolved A=[$$A]";                                                        \
	 grep -q BADCOOKIE /tmp/cookie_stub.log || { echo "  FAIL  upstream never sent BADCOOKIE"; cat /tmp/cookie_stub.log; exit 1; }; \
	 grep -q "ANSWER cookie-validated" /tmp/cookie_stub.log || { echo "  FAIL  resolverd never retried with a valid Server Cookie"; cat /tmp/cookie_stub.log; exit 1; }; \
	 test "$$A" = "203.0.113.77" || { echo "  FAIL  resolverd did not return the cookie-gated answer"; cat /tmp/resolverd_cookie.log; exit 1; }; \
	 echo "  OK  resolverd completed the RFC 7873 cookie handshake and resolved"

# =============================================================================
# Clean
# =============================================================================
clean:
	@echo "  CLEAN"
	rm -f $(BIN) $(BIN_DEBUG) certd certd_debug mdnsd mdnsd_debug apid apid_debug \
	      resolverd resolverd_debug \
	      $(SIG_GPG) $(SIG_OSSL) \
	      tests/test_dnssec_verify tests/test_rollover tests/test_name_from_wire \
	      fuzz/fuzz_name_from_wire
	@echo "  done"

# =============================================================================
# Help
# =============================================================================
help:
	@echo ""
	@echo "dns_server build system"
	@echo ""
	@echo "  make              Production build: optimised, stripped, GPG-signed"
	@echo "  make debug        Debug build: ASan/UBSan, full symbols, not stripped"
	@echo "  make certd        certd sidecar (ACME/EST), hardened production build"
	@echo "  make certd_debug  certd sidecar, ASan/UBSan debug build"
	@echo "  make mdnsd        mDNS/DNS-SD responder, hardened production build"
	@echo "  make mdnsd_debug  mDNS responder, ASan/UBSan debug build"
	@echo "  make apid         HTTP/HTTPS front (DoH + mgmt), hardened production build"
	@echo "  make apid_debug   apid front, ASan/UBSan debug build"
	@echo "  make resolverd       Recursive/forwarding resolver (recursive role), hardened build"
	@echo "  make resolverd_debug Resolver, ASan/UBSan debug build"
	@echo "  make sign         (Re-)sign the existing production binary with GPG"
	@echo "  make sign-openssl Sign with OpenSSL Ed25519 key (keys/codesign.key.pem)"
	@echo "  make verify       Verify GPG and/or OpenSSL signatures"
	@echo "  make install      Install binary + signature to \$$(DESTDIR)\$$(PREFIX)/bin"
	@echo "  make uninstall    Remove installed files"
	@echo "  make check        Quick smoke-test (needs Valkey)"
	@echo "  make check-catalog   RFC 9432 catalog provision/deprovision (needs Valkey + dig)"
	@echo "  make check-forwarder Out-of-zone forwarding (needs Valkey + dig + python3)"
	@echo "  make check-lb        A/AAAA load-balancing rotation (needs Valkey + dig)"
	@echo "  make check-axfr      AXFR transfers runtime records (needs Valkey + dig)"
	@echo "  make check-dot-mtls  mTLS on the DoT/transfer listener (needs Valkey + openssl)"
	@echo "  make check-ddns-acl  DDNS suffix ACL + serial-churn skip (needs Valkey + nsupdate)"
	@echo "  make check-role      Secondary role guards: UPDATE→NOTAUTH + no keygen (needs Valkey + nsupdate)"
	@echo "  make check-xfr-client Secondary AXFR pull from master (needs Valkey + dig + python3)"
	@echo "  make check-xfr-refresh NOTIFY re-pull + SOA expire (needs Valkey + dig + python3)"
	@echo "  make check-xfr-tsig  Transfer TSIG sign+verify (needs Valkey + dig + python3)"
	@echo "  make check-resolverd resolverd caching proxy → dnsd (needs Valkey + dig)"
	@echo "  make check-resolverd-cache resolverd Valkey cache-load regression (needs Valkey + dig)"
	@echo "  make check-resolverd-cookie resolverd RFC 7873 cookie exchange (needs dig + python3)"
	@echo "  make clean        Remove build artefacts"
	@echo "  make gen-signing-key  Generate OpenSSL Ed25519 code-signing key pair"
	@echo "  make help         This message"
	@echo ""
	@echo "Override variables:"
	@echo "  CC=clang          Use Clang instead of GCC"
	@echo "  GPG_KEY=<id>      GPG key fingerprint or email to sign with"
	@echo "  OSSL_INC=<path>   OpenSSL include directory"
	@echo "  OSSL_LIB=<path>   OpenSSL library directory"
	@echo "  PREFIX=<path>     Install prefix (default: /usr/local)"
	@echo "  DESTDIR=<path>    Staging directory for packagers"
	@echo ""
	@echo "Example — build for packaging:"
	@echo "  make prod GPG_KEY=ops@example.com DESTDIR=\$$(pwd)/pkg PREFIX=/usr"
	@echo ""
